#!/usr/bin/env python3
"""
GPU Hardware Intrinsic Profiling Agent
======================================

Main entry point for the MLSys course project.

This agent autonomously probes GPU hardware characteristics using
CUDA micro-benchmarks and NVIDIA Nsight Compute (ncu) profiling.
It produces accurate measurements even under non-standard configurations
such as frequency locking, SM masking, or spoofed device properties.

Architecture:
  1. Reads /target/target_spec.json to determine which metrics to measure
     and (optionally) which executable to profile for bottleneck analysis
  2. Compiles and runs CUDA micro-benchmark probes (sources generated by LLM)
  3. Parses raw output and applies statistical analysis
  4. Cross-verifies results using multiple methods (probes, ncu, nvidia-smi)
  5. Detects anomalies (frequency locking, SM masking)
  6. If "run" is specified in target_spec.json, performs kernel bottleneck
     analysis on that executable via ncu (Sections 1.1-1.6)
  7. Outputs a single /workspace/output.json with all measurements,
     kernel analysis, and reasoning

Usage:
  python3 agent.py                                   # eval defaults
  python3 agent.py --target-spec /path/to/spec.json --output /path/to/output.json
  python3 agent.py --kernel ./my_cuda_binary         # standalone kernel analysis
"""

import argparse
import json
import os
import sys
import logging
import tempfile

from src.hardware_prober import HardwareProber
from src.kernel_analyzer import KernelAnalyzer
from src.lora_optimizer import LoRAOptimizationAgent
from src.reasoning import ReasoningEngine
from src import utils

# Configure logging: console + tmp/agent.log (keeps /workspace/ clean)
_agent_log = os.path.join(tempfile.gettempdir(), 'agent.log')
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s',
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(_agent_log, mode='w'),
    ]
)
logger = logging.getLogger('GPUAgent')


def load_target_spec(spec_path: str) -> dict:
    """Load and validate target_spec.json.

    Returns the parsed dict which may contain:
      - "targets": list of hardware metric names to probe
      - "run":     path to a CUDA binary to profile (optional)
    """
    if not os.path.exists(spec_path):
        logger.error(f"Target spec not found: {spec_path}")
        return {}
    with open(spec_path, 'r') as f:
        return json.load(f)


def run_hardware_probing(targets: list, args, reasoning: ReasoningEngine) -> dict:
    """
    Phase 1: Hardware Intrinsic Probing

    Runs micro-benchmarks for the requested target metrics and returns
    the measured values.
    """
    logger.info("=" * 60)
    logger.info("Phase 1: Hardware Intrinsic Profiling")
    logger.info("=" * 60)

    if not targets:
        logger.warning("No hardware target metrics requested — skipping Phase 1")
        return {}

    logger.info(f"Target metrics ({len(targets)}): {targets}")
    reasoning.log_step(
        'initialization',
        f'Loaded target_spec.json with {len(targets)} metrics',
        data={'targets': targets}
    )

    # Initialize the hardware prober
    prober = HardwareProber(
        probe_dir=args.probe_dir,
        build_dir=args.build_dir,
        num_trials=args.trials,
        reasoning=reasoning,
    )

    # Run all probes and collect results
    results = prober.probe_all(targets)

    return results


def run_kernel_analysis(binary_path: str, args, reasoning: ReasoningEngine,
                        kernel_name: str = None) -> dict:
    """
    Phase 2: Kernel Performance Analysis

    Uses ncu to profile a CUDA kernel and diagnose bottlenecks
    following the Section 1.1-1.6 analysis methodology.

    The binary_path can come from:
      - the "run" field in target_spec.json   (evaluation workflow)
      - the --kernel CLI flag                 (manual / standalone)
    """
    logger.info("=" * 60)
    logger.info("Phase 2: Kernel Bottleneck Analysis")
    logger.info("=" * 60)
    logger.info(f"Binary to profile: {binary_path}")

    # If the user supplied a .cu source file, compile it first
    if binary_path.endswith('.cu'):
        from src.probe_manager import ProbeManager
        pm = ProbeManager(probe_dir=os.path.dirname(binary_path) or '.',
                          build_dir=args.build_dir)
        probe_name = os.path.splitext(os.path.basename(binary_path))[0]
        compiled = pm.compile(probe_name, source_path=binary_path)
        if not compiled:
            logger.error(f"Failed to compile {binary_path}")
            return {'error': f'compilation failed for {binary_path}'}
        binary_path = compiled

    analyzer = KernelAnalyzer(reasoning=reasoning)
    analysis = analyzer.analyze(binary_path, kernel_name=kernel_name)

    return analysis


def run_lora_optimization(args) -> dict:
    """
    Phase 2: Agentic LoRA optimization.

    Generates candidate single-file CUDA / PyTorch extensions, benchmarks them
    on synthetic inputs inside the public evaluation range, and keeps the best
    validated implementation at args.optimized_path.
    """
    logger.info("=" * 60)
    logger.info("Phase 2: Agentic LoRA Optimization")
    logger.info("=" * 60)

    benchmark_sizes = [
        int(chunk.strip())
        for chunk in args.benchmark_sizes.split(',')
        if chunk.strip()
    ]

    optimizer = LoRAOptimizationAgent(
        project_root=os.path.dirname(os.path.abspath(__file__)),
        build_dir=args.build_dir,
        optimized_path=args.optimized_path,
        summary_path=args.summary_path,
        benchmark_sizes=benchmark_sizes,
        benchmark_warmup=args.benchmark_warmup,
        benchmark_iters=args.benchmark_iters,
        search_rounds=args.search_rounds,
        time_budget_seconds=int(args.time_budget_minutes * 60),
        use_llm=not args.skip_llm,
    )
    return optimizer.run()


def main():
    parser = argparse.ArgumentParser(
        description='GPU Hardware Intrinsic Profiling Agent',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Run the full evaluation workflow (reads targets + executable from spec)
  python3 agent.py --target-spec target_spec.json --output results.json

  # Analyze a specific CUDA kernel for bottlenecks (standalone)
  python3 agent.py --kernel ./matmul

  # Both: probe hardware and analyze kernel
  python3 agent.py --target-spec target_spec.json --kernel ./matmul

  # Customize probe parameters
  python3 agent.py --trials 10 --target-spec target_spec.json
        """
    )

    parser.add_argument(
        '--phase', type=str, default='auto', choices=['auto', 'phase1', 'phase2'],
        help='Which project phase to run (default: auto)'
    )
    parser.add_argument(
        '--target-spec', type=str, default='/target/target_spec.json',
        help='Path to target_spec.json (default: /target/target_spec.json)'
    )
    parser.add_argument(
        '--output', type=str, default='/workspace/output.json',
        help='Path to single consolidated output file (default: /workspace/output.json)'
    )
    parser.add_argument(
        '--kernel', type=str, default=None,
        help='Path to CUDA kernel binary to analyze (overrides "run" in spec)'
    )
    parser.add_argument(
        '--kernel-name', type=str, default=None,
        help='Specific kernel function name to profile (optional)'
    )
    parser.add_argument(
        '--probe-dir', type=str, default='probes',
        help='Directory containing CUDA probe source files (default: probes)'
    )
    parser.add_argument(
        '--build-dir', type=str, default='build',
        help='Directory for compiled probe binaries (default: build)'
    )
    parser.add_argument(
        '--trials', type=int, default=5,
        help='Number of repeated trials per measurement (default: 5)'
    )
    parser.add_argument(
        '--optimized-path', type=str, default='optimized_lora.cu',
        help='Phase 2 output path for the current best LoRA implementation'
    )
    parser.add_argument(
        '--summary-path', type=str, default='phase2_summary.md',
        help='Phase 2 markdown summary path'
    )
    parser.add_argument(
        '--search-rounds', type=int, default=5,
        help='Phase 2 candidate budget (default: 5)'
    )
    parser.add_argument(
        '--time-budget-minutes', type=float, default=20.0,
        help='Phase 2 search time budget in minutes (default: 20)'
    )
    parser.add_argument(
        '--benchmark-sizes', type=str, default='3584,4096,4608',
        help='Comma-separated Phase 2 benchmark sizes (default: 3584,4096,4608)'
    )
    parser.add_argument(
        '--benchmark-warmup', type=int, default=5,
        help='Phase 2 warmup iterations per benchmark size (default: 5)'
    )
    parser.add_argument(
        '--benchmark-iters', type=int, default=15,
        help='Phase 2 timed iterations per benchmark size (default: 15)'
    )
    parser.add_argument(
        '--skip-llm', action='store_true',
        help='Disable the LLM planner for Phase 2 candidate ordering'
    )

    args = parser.parse_args()

    # Resolve paths relative to script directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    if not os.path.isabs(args.probe_dir):
        args.probe_dir = os.path.join(script_dir, args.probe_dir)
    if not os.path.isabs(args.build_dir):
        args.build_dir = os.path.join(script_dir, args.build_dir)
    if not os.path.isabs(args.target_spec):
        args.target_spec = os.path.join(script_dir, args.target_spec)
    if not os.path.isabs(args.output):
        args.output = os.path.join(script_dir, args.output)
    if not os.path.isabs(args.optimized_path):
        args.optimized_path = os.path.join(script_dir, args.optimized_path)
    if not os.path.isabs(args.summary_path):
        args.summary_path = os.path.join(script_dir, args.summary_path)

    logger.info("=" * 60)
    logger.info("GPU Hardware Intrinsic Profiling Agent")
    logger.info("=" * 60)
    logger.info(f"Phase: {args.phase}")
    logger.info(f"Probe directory: {args.probe_dir}")
    logger.info(f"Build directory: {args.build_dir}")
    logger.info(f"Target spec: {args.target_spec}")
    logger.info(f"Output: {args.output}")
    logger.info(f"Optimized LoRA path: {args.optimized_path}")

    target_spec = {}
    if os.path.exists(args.target_spec):
        target_spec = load_target_spec(args.target_spec)

    phase = args.phase
    if phase == 'auto':
        if target_spec.get('targets') or target_spec.get('run') or args.kernel:
            phase = 'phase1'
        else:
            phase = 'phase2'

    if phase == 'phase2':
        result = run_lora_optimization(args)
        with open(args.output, 'w') as f:
            json.dump(result, f, indent=2, default=str)
        logger.info(f"Phase 2 results written to {args.output}")
        return

    # Initialize reasoning engine
    reasoning = ReasoningEngine()

    # Detect environment
    reasoning.log_step('startup', 'Agent starting - detecting environment')
    gpu_info = utils.get_gpu_info()
    reasoning.log_step('startup', 'GPU environment detected', data=gpu_info)

    # ------------------------------------------------------------------ #
    # Load the evaluation spec — this single file drives the entire run   #
    # ------------------------------------------------------------------ #
    if os.path.exists(args.target_spec):
        reasoning.log_step(
            'initialization',
            f'Loaded target_spec.json: keys={list(target_spec.keys())}',
            data=target_spec,
        )

    hw_targets = target_spec.get('targets', [])
    if not hw_targets:
        logger.info('No targets in target_spec.json — Phase 1 (hardware probing) will be skipped')

    # The "run" field tells us which executable to profile for Sections 1.1-1.6
    run_binary = target_spec.get('run', None)
    if not run_binary:
        logger.info("No 'run' field in target_spec.json — Phase 2 (kernel analysis) will be skipped")
    # CLI --kernel overrides the spec's "run" field
    kernel_binary = args.kernel or run_binary

    if kernel_binary:
        # Resolve relative paths against the spec-file directory first,
        # then against the script directory.
        if not os.path.isabs(kernel_binary):
            spec_dir = os.path.dirname(args.target_spec)
            candidate = os.path.join(spec_dir, kernel_binary)
            if os.path.exists(candidate):
                kernel_binary = candidate
            elif sys.platform == 'win32' and os.path.exists(candidate + '.exe'):
                kernel_binary = candidate + '.exe'
            else:
                kernel_binary = os.path.join(script_dir, kernel_binary)

        # On Windows, append .exe if the path has no extension and the .exe exists
        if sys.platform == 'win32' and not os.path.splitext(kernel_binary)[1]:
            if not os.path.exists(kernel_binary) and os.path.exists(kernel_binary + '.exe'):
                kernel_binary = kernel_binary + '.exe'

    # Guard: if the binary doesn't exist, skip Phase 2 gracefully instead of crashing
    if kernel_binary and not kernel_binary.endswith('.cu'):
        if not os.path.isfile(kernel_binary):
            logger.warning(
                f"Kernel binary not found: '{kernel_binary}' — "
                f"Phase 2 (kernel analysis) will be skipped. "
                f"Ensure run.sh successfully compiled the CUDA source."
            )
            kernel_binary = None

    logger.info(f"Hardware targets: {hw_targets}")
    logger.info(f"Kernel to profile: {kernel_binary or '(none)'}")

    all_results = {}

    # ------------------------------------------------------------------ #
    # Phase 1: Hardware Probing (if any hardware targets requested)       #
    # ------------------------------------------------------------------ #
    if hw_targets:
        hw_results = run_hardware_probing(hw_targets, args, reasoning)
        all_results.update(hw_results)

    # ------------------------------------------------------------------ #
    # Phase 2: Kernel Analysis (from spec "run" or CLI --kernel)          #
    # ------------------------------------------------------------------ #
    if kernel_binary:
        kernel_analysis = run_kernel_analysis(
            kernel_binary, args, reasoning,
            kernel_name=args.kernel_name,
        )
        # Embed the full kernel analysis JSON inside the single output file.
        # No separate *_kernel_analysis.json or *_kernel_report.md is written —
        # the evaluation environment must see exactly one output.* file.
        all_results['_kernel_analysis_full'] = kernel_analysis
        all_results['_kernel_analysis'] = kernel_analysis.get('summary', {})
        llm_report = kernel_analysis.get('llm_report', '')
        if llm_report:
            all_results['_kernel_report'] = llm_report

    # Write final results
    output_data = {}

    def _round_metric(key: str, value: float) -> float:
        """Apply context-appropriate rounding for a named metric."""
        if 'cycles' in key or 'mhz' in key:
            return round(value, 1)
        if 'gbps' in key:
            return round(value, 2)
        if 'kb' in key or 'mb' in key:
            return round(value, 1)
        return round(value, 2)

    # Numeric metric results — only the metrics explicitly requested in
    # target_spec.targets are emitted.  Extra data that the probes happen
    # to compute internally is intentionally excluded.
    for key in hw_targets:
        value = all_results.get(key)
        if value is None:
            continue
        output_data[key] = _round_metric(key, value) if isinstance(value, float) else value

    # Phase-2 analysis blobs (always _ -prefixed, kept separate from metrics)
    for key, value in all_results.items():
        if key.startswith('_') and value is not None:
            output_data[key] = value

    # Add reasoning metadata (for Engineering Reasoning scoring)
    # LLM-authored narratives go into the top-level fields the grader reads
    reasoning_text = reasoning.get_reasoning_text()
    methodology_text = reasoning.get_methodology_text()

    output_data['_reasoning'] = reasoning_text if reasoning_text else reasoning.get_summary()
    output_data['_methodology'] = methodology_text if methodology_text else reasoning.get_methodology()

    # Detailed evidence log for LLM-as-a-Judge evaluation
    summary = reasoning.get_summary()
    output_data['_log'] = {
        'steps': summary.get('steps', []),
        'anomalies': summary.get('anomalies', []),
        'cross_verifications': summary.get('cross_verifications', []),
        'methodology_records': reasoning.get_methodology(),
        'elapsed_seconds': summary.get('elapsed_seconds', 0),
    }

    with open(args.output, 'w') as f:
        json.dump(output_data, f, indent=2, default=str)
    logger.info(f"Results written to {args.output}")

    # Print human-readable report
    report = reasoning.format_report()
    print("\n" + report)

    # Print final results summary
    logger.info("=" * 60)
    logger.info("FINAL RESULTS")
    logger.info("=" * 60)
    for key, value in output_data.items():
        if not key.startswith('_'):
            logger.info(f"  {key}: {value}")

    logger.info("=" * 60)
    logger.info("Agent finished successfully.")
    logger.info("=" * 60)


if __name__ == '__main__':
    main()
