"""
Phase 2 LoRA optimization agent.

Architecture:
  Stage 1 – Template Search
    Evaluates a fixed library of hand-written CUDA extension templates that
    explore different optimisation axes (stream overlap, pre-allocation,
    contiguous transpose, addmm vs mm+add_).  The best correct variant
    becomes the starting point for Stage 2.

  Stage 2 – LLM-driven Iterative Improvement
    Feeds the current best CUDA code and its benchmark results to an LLM,
    which proposes concrete code modifications.  Each proposal is compiled,
    validated, and benchmarked.  If it beats the current best, it replaces
    optimized_lora.cu.  The loop repeats until the time budget is exhausted.

All templates use PyTorch's at::mm / at::addmm so that the computation
follows the exact same cuBLAS code-path as the reference implementation,
guaranteeing bit-exact correctness.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import importlib.util
import json
import logging
import math
import os
from pathlib import Path
import re
import subprocess
import textwrap
import time
from typing import Any, Optional

from . import utils

logger = logging.getLogger('GPUAgent.LoRAOptimizer')

_llm_client = None


def _get_llm():
    global _llm_client
    if _llm_client is not None:
        return _llm_client
    try:
        from .llm_client import LLMClient
        _llm_client = LLMClient(enable_thinking=False)
        _llm_client._client.timeout = 120
    except Exception as exc:
        logger.warning('LLM client unavailable: %s', exc)
        _llm_client = None
    return _llm_client


# =========================================================================
# Template library (Stage 1)
# =========================================================================

_COMMON_HEADER = textwrap.dedent(r'''
// Auto-generated by Phase 2 LoRA optimization agent.
// Candidate config: __CONFIG_JSON__
#include <torch/extension.h>
#include <ATen/ATen.h>
#include <ATen/cuda/CUDAContext.h>
#include <c10/cuda/CUDAStream.h>
#include <c10/cuda/CUDAGuard.h>
#include <cuda_runtime.h>

#define CUDA_CHECK(expr) TORCH_CHECK((expr) == cudaSuccess, \
    "CUDA error: ", cudaGetErrorString(expr))
''').strip()

_PYBIND_FOOTER = textwrap.dedent(r'''
PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
  m.def("forward", &forward, "Optimized LoRA forward");
}
''').strip()

# ---- Template A: baseline sequential (single stream) ----
TEMPLATE_A = _COMMON_HEADER + "\n\n" + textwrap.dedent(r'''
torch::Tensor forward(torch::Tensor W,
                      torch::Tensor X,
                      torch::Tensor A,
                      torch::Tensor B) {
  TORCH_CHECK(W.is_cuda() && X.is_cuda() && A.is_cuda() && B.is_cuda(),
              "All tensors must be CUDA tensors");
  TORCH_CHECK(W.is_contiguous() && X.is_contiguous() &&
              A.is_contiguous() && B.is_contiguous(),
              "All tensors must be contiguous");
  at::Tensor Y = at::mm(W, X);
  at::Tensor tmp = at::mm(B.t(), X);
  at::addmm_out(Y, Y, A, tmp, 1.0, 1.0);
  return Y;
}
''').strip() + "\n\n" + _PYBIND_FOOTER + "\n"

# ---- Template B: dual-stream overlap (W@X || B^T@X) ----
TEMPLATE_B = _COMMON_HEADER + "\n\n" + textwrap.dedent(r'''
torch::Tensor forward(torch::Tensor W,
                      torch::Tensor X,
                      torch::Tensor A,
                      torch::Tensor B) {
  TORCH_CHECK(W.is_cuda() && X.is_cuda() && A.is_cuda() && B.is_cuda(),
              "All tensors must be CUDA tensors");
  TORCH_CHECK(W.is_contiguous() && X.is_contiguous() &&
              A.is_contiguous() && B.is_contiguous(),
              "All tensors must be contiguous");
  const int device = W.get_device();
  c10::cuda::CUDAGuard guard(device);
  cudaStream_t main_stream = c10::cuda::getCurrentCUDAStream(device);
  auto aux_stream = c10::cuda::getStreamFromPool(false, device);
  cudaEvent_t evt_btx;
  CUDA_CHECK(cudaEventCreateWithFlags(&evt_btx, cudaEventDisableTiming));
  at::Tensor Y = at::mm(W, X);
  at::Tensor tmp;
  {
    c10::cuda::CUDAStreamGuard sg(aux_stream);
    tmp = at::mm(B.t(), X);
    CUDA_CHECK(cudaEventRecord(evt_btx, aux_stream.stream()));
  }
  CUDA_CHECK(cudaStreamWaitEvent(main_stream, evt_btx, 0));
  at::addmm_out(Y, Y, A, tmp, 1.0, 1.0);
  CUDA_CHECK(cudaEventDestroy(evt_btx));
  return Y;
}
''').strip() + "\n\n" + _PYBIND_FOOTER + "\n"

# ---- Template C: pre-transpose B, dual-stream ----
TEMPLATE_C = _COMMON_HEADER + "\n\n" + textwrap.dedent(r'''
torch::Tensor forward(torch::Tensor W,
                      torch::Tensor X,
                      torch::Tensor A,
                      torch::Tensor B) {
  TORCH_CHECK(W.is_cuda() && X.is_cuda() && A.is_cuda() && B.is_cuda(),
              "All tensors must be CUDA tensors");
  TORCH_CHECK(W.is_contiguous() && X.is_contiguous() &&
              A.is_contiguous() && B.is_contiguous(),
              "All tensors must be contiguous");
  const int device = W.get_device();
  c10::cuda::CUDAGuard guard(device);
  cudaStream_t main_stream = c10::cuda::getCurrentCUDAStream(device);
  auto aux_stream = c10::cuda::getStreamFromPool(false, device);
  cudaEvent_t evt_btx;
  CUDA_CHECK(cudaEventCreateWithFlags(&evt_btx, cudaEventDisableTiming));
  at::Tensor Bt;
  {
    c10::cuda::CUDAStreamGuard sg(aux_stream);
    Bt = B.t().contiguous();
  }
  at::Tensor Y = at::mm(W, X);
  at::Tensor tmp;
  {
    c10::cuda::CUDAStreamGuard sg(aux_stream);
    tmp = at::mm(Bt, X);
    CUDA_CHECK(cudaEventRecord(evt_btx, aux_stream.stream()));
  }
  CUDA_CHECK(cudaStreamWaitEvent(main_stream, evt_btx, 0));
  at::addmm_out(Y, Y, A, tmp, 1.0, 1.0);
  CUDA_CHECK(cudaEventDestroy(evt_btx));
  return Y;
}
''').strip() + "\n\n" + _PYBIND_FOOTER + "\n"

# ---- Template D: mm + add_ instead of addmm_out ----
TEMPLATE_D = _COMMON_HEADER + "\n\n" + textwrap.dedent(r'''
torch::Tensor forward(torch::Tensor W,
                      torch::Tensor X,
                      torch::Tensor A,
                      torch::Tensor B) {
  TORCH_CHECK(W.is_cuda() && X.is_cuda() && A.is_cuda() && B.is_cuda(),
              "All tensors must be CUDA tensors");
  TORCH_CHECK(W.is_contiguous() && X.is_contiguous() &&
              A.is_contiguous() && B.is_contiguous(),
              "All tensors must be contiguous");
  const int device = W.get_device();
  c10::cuda::CUDAGuard guard(device);
  cudaStream_t main_stream = c10::cuda::getCurrentCUDAStream(device);
  auto aux_stream = c10::cuda::getStreamFromPool(false, device);
  cudaEvent_t evt_btx;
  CUDA_CHECK(cudaEventCreateWithFlags(&evt_btx, cudaEventDisableTiming));
  at::Tensor Y = at::mm(W, X);
  at::Tensor tmp;
  {
    c10::cuda::CUDAStreamGuard sg(aux_stream);
    tmp = at::mm(B.t(), X);
    CUDA_CHECK(cudaEventRecord(evt_btx, aux_stream.stream()));
  }
  CUDA_CHECK(cudaStreamWaitEvent(main_stream, evt_btx, 0));
  at::Tensor lora_out = at::mm(A, tmp);
  Y.add_(lora_out);
  CUDA_CHECK(cudaEventDestroy(evt_btx));
  return Y;
}
''').strip() + "\n\n" + _PYBIND_FOOTER + "\n"

# ---- Template E: triple-stream ----
TEMPLATE_E = _COMMON_HEADER + "\n\n" + textwrap.dedent(r'''
torch::Tensor forward(torch::Tensor W,
                      torch::Tensor X,
                      torch::Tensor A,
                      torch::Tensor B) {
  TORCH_CHECK(W.is_cuda() && X.is_cuda() && A.is_cuda() && B.is_cuda(),
              "All tensors must be CUDA tensors");
  TORCH_CHECK(W.is_contiguous() && X.is_contiguous() &&
              A.is_contiguous() && B.is_contiguous(),
              "All tensors must be contiguous");
  const int device = W.get_device();
  c10::cuda::CUDAGuard guard(device);
  cudaStream_t main_stream = c10::cuda::getCurrentCUDAStream(device);
  auto stream1 = c10::cuda::getStreamFromPool(false, device);
  auto stream2 = c10::cuda::getStreamFromPool(false, device);
  const auto d = W.size(0);
  const auto r = A.size(1);
  auto Y = at::empty({d, d}, W.options());
  auto tmp = at::empty({r, d}, W.options());
  cudaEvent_t evt_wx, evt_btx;
  CUDA_CHECK(cudaEventCreateWithFlags(&evt_wx, cudaEventDisableTiming));
  CUDA_CHECK(cudaEventCreateWithFlags(&evt_btx, cudaEventDisableTiming));
  {
    c10::cuda::CUDAStreamGuard sg(stream1);
    at::mm_out(Y, W, X);
    CUDA_CHECK(cudaEventRecord(evt_wx, stream1.stream()));
  }
  {
    c10::cuda::CUDAStreamGuard sg(stream2);
    at::mm_out(tmp, B.t(), X);
    CUDA_CHECK(cudaEventRecord(evt_btx, stream2.stream()));
  }
  CUDA_CHECK(cudaStreamWaitEvent(main_stream, evt_wx, 0));
  CUDA_CHECK(cudaStreamWaitEvent(main_stream, evt_btx, 0));
  at::addmm_out(Y, Y, A, tmp, 1.0, 1.0);
  CUDA_CHECK(cudaEventDestroy(evt_wx));
  CUDA_CHECK(cudaEventDestroy(evt_btx));
  return Y;
}
''').strip() + "\n\n" + _PYBIND_FOOTER + "\n"

# ---- Template F: single stream, pre-alloc mm_out ----
TEMPLATE_F = _COMMON_HEADER + "\n\n" + textwrap.dedent(r'''
torch::Tensor forward(torch::Tensor W,
                      torch::Tensor X,
                      torch::Tensor A,
                      torch::Tensor B) {
  TORCH_CHECK(W.is_cuda() && X.is_cuda() && A.is_cuda() && B.is_cuda(),
              "All tensors must be CUDA tensors");
  TORCH_CHECK(W.is_contiguous() && X.is_contiguous() &&
              A.is_contiguous() && B.is_contiguous(),
              "All tensors must be contiguous");
  const auto d = W.size(0);
  const auto r = A.size(1);
  auto Y = at::empty({d, d}, W.options());
  auto tmp = at::empty({r, d}, W.options());
  at::mm_out(Y, W, X);
  at::mm_out(tmp, B.t(), X);
  at::addmm_out(Y, Y, A, tmp, 1.0, 1.0);
  return Y;
}
''').strip() + "\n\n" + _PYBIND_FOOTER + "\n"

# ---- Template G: dual-stream + pre-alloc + mm_out ----
TEMPLATE_G = _COMMON_HEADER + "\n\n" + textwrap.dedent(r'''
torch::Tensor forward(torch::Tensor W,
                      torch::Tensor X,
                      torch::Tensor A,
                      torch::Tensor B) {
  TORCH_CHECK(W.is_cuda() && X.is_cuda() && A.is_cuda() && B.is_cuda(),
              "All tensors must be CUDA tensors");
  TORCH_CHECK(W.is_contiguous() && X.is_contiguous() &&
              A.is_contiguous() && B.is_contiguous(),
              "All tensors must be contiguous");
  const int device = W.get_device();
  c10::cuda::CUDAGuard guard(device);
  cudaStream_t main_stream = c10::cuda::getCurrentCUDAStream(device);
  auto aux_stream = c10::cuda::getStreamFromPool(false, device);
  const auto d = W.size(0);
  const auto r = A.size(1);
  auto Y = at::empty({d, d}, W.options());
  auto tmp = at::empty({r, d}, W.options());
  cudaEvent_t evt_btx;
  CUDA_CHECK(cudaEventCreateWithFlags(&evt_btx, cudaEventDisableTiming));
  at::mm_out(Y, W, X);
  {
    c10::cuda::CUDAStreamGuard sg(aux_stream);
    at::mm_out(tmp, B.t(), X);
    CUDA_CHECK(cudaEventRecord(evt_btx, aux_stream.stream()));
  }
  CUDA_CHECK(cudaStreamWaitEvent(main_stream, evt_btx, 0));
  at::addmm_out(Y, Y, A, tmp, 1.0, 1.0);
  CUDA_CHECK(cudaEventDestroy(evt_btx));
  return Y;
}
''').strip() + "\n\n" + _PYBIND_FOOTER + "\n"

# ---- Template H: dual-stream + contiguous Bt + mm_out ----
TEMPLATE_H = _COMMON_HEADER + "\n\n" + textwrap.dedent(r'''
torch::Tensor forward(torch::Tensor W,
                      torch::Tensor X,
                      torch::Tensor A,
                      torch::Tensor B) {
  TORCH_CHECK(W.is_cuda() && X.is_cuda() && A.is_cuda() && B.is_cuda(),
              "All tensors must be CUDA tensors");
  TORCH_CHECK(W.is_contiguous() && X.is_contiguous() &&
              A.is_contiguous() && B.is_contiguous(),
              "All tensors must be contiguous");
  const int device = W.get_device();
  c10::cuda::CUDAGuard guard(device);
  cudaStream_t main_stream = c10::cuda::getCurrentCUDAStream(device);
  auto aux_stream = c10::cuda::getStreamFromPool(false, device);
  const auto d = W.size(0);
  const auto r = A.size(1);
  auto Y = at::empty({d, d}, W.options());
  auto tmp = at::empty({r, d}, W.options());
  cudaEvent_t evt_btx;
  CUDA_CHECK(cudaEventCreateWithFlags(&evt_btx, cudaEventDisableTiming));
  at::mm_out(Y, W, X);
  {
    c10::cuda::CUDAStreamGuard sg(aux_stream);
    at::Tensor Bt = B.t().contiguous();
    at::mm_out(tmp, Bt, X);
    CUDA_CHECK(cudaEventRecord(evt_btx, aux_stream.stream()));
  }
  CUDA_CHECK(cudaStreamWaitEvent(main_stream, evt_btx, 0));
  at::addmm_out(Y, Y, A, tmp, 1.0, 1.0);
  CUDA_CHECK(cudaEventDestroy(evt_btx));
  return Y;
}
''').strip() + "\n\n" + _PYBIND_FOOTER + "\n"


TEMPLATE_LIBRARY: dict[str, str] = {
    'baseline_sequential': TEMPLATE_A,
    'dual_stream_overlap': TEMPLATE_B,
    'dual_stream_pretranspose': TEMPLATE_C,
    'dual_stream_mm_add': TEMPLATE_D,
    'triple_stream_prealloc': TEMPLATE_E,
    'sequential_prealloc': TEMPLATE_F,
    'dual_stream_prealloc': TEMPLATE_G,
    'dual_stream_prealloc_contig': TEMPLATE_H,
}


# =========================================================================
# Data classes
# =========================================================================

@dataclass(frozen=True)
class CandidateConfig:
    template_name: str
    block_size: Optional[int]
    rationale: str

    @property
    def name(self) -> str:
        if self.block_size is None:
            return self.template_name
        return f'{self.template_name}_bs{self.block_size}'

    def to_dict(self) -> dict[str, Any]:
        return {
            'name': self.name,
            'template_name': self.template_name,
            'block_size': self.block_size,
            'rationale': self.rationale,
        }

    @property
    def fingerprint(self) -> str:
        payload = json.dumps(self.to_dict(), sort_keys=True)
        return hashlib.md5(payload.encode('utf-8')).hexdigest()[:8]


# =========================================================================
# Code generation
# =========================================================================

class LoRACodegen:
    """Render templates and LLM-generated code."""

    @staticmethod
    def render(config: CandidateConfig) -> str:
        template = TEMPLATE_LIBRARY[config.template_name]
        return template.replace(
            '__CONFIG_JSON__',
            json.dumps(config.to_dict(), sort_keys=True),
        )

    @staticmethod
    def extract_cuda_from_llm(llm_response: str) -> Optional[str]:
        """Extract CUDA source code from an LLM response.

        Looks for code inside ```cpp or ```cuda fences first, then falls
        back to ```...``` fences that contain typical CUDA markers.
        """
        # Try explicit language fences first
        for lang in ('cpp', 'cuda', 'c++', 'c'):
            pattern = rf'```{lang}\s*\n(.*?)```'
            m = re.search(pattern, llm_response, re.DOTALL | re.IGNORECASE)
            if m:
                code = m.group(1).strip()
                if 'PYBIND11_MODULE' in code and 'forward' in code:
                    return code

        # Generic fence
        pattern = r'```\s*\n(.*?)```'
        for m in re.finditer(pattern, llm_response, re.DOTALL):
            code = m.group(1).strip()
            if 'PYBIND11_MODULE' in code and 'forward' in code:
                return code

        # No fences – check if the whole response looks like code
        if ('PYBIND11_MODULE' in llm_response and
                'forward' in llm_response and
                '#include' in llm_response):
            return llm_response.strip()

        return None


# =========================================================================
# Benchmark harness
# =========================================================================

class LoRABenchmarkHarness:
    """Compile, validate, and benchmark generated candidates."""

    def __init__(self, build_dir: Path, benchmark_sizes: list[int],
                 warmup: int, iters: int):
        self.build_dir = build_dir
        self.benchmark_sizes = benchmark_sizes
        self.warmup = warmup
        self.iters = iters

    @staticmethod
    def torch_available() -> bool:
        return importlib.util.find_spec('torch') is not None

    @staticmethod
    def _import_torch():
        import torch
        from torch.utils.cpp_extension import load
        return torch, load

    def evaluate(self, candidate_name: str, source_path: Path,
                 fingerprint: str = '') -> dict[str, Any]:
        """Compile and benchmark a single .cu file.

        Returns a dict with keys: passed, score, per_size, compile_seconds.
        """
        torch, load = self._import_torch()
        if not torch.cuda.is_available():
            raise RuntimeError('CUDA not available')

        module_name = f'lora_{candidate_name}_{fingerprint}'[:60]
        # sanitise for C identifier
        module_name = re.sub(r'[^a-zA-Z0-9_]', '_', module_name)
        module_build_dir = self.build_dir / module_name
        module_build_dir.mkdir(parents=True, exist_ok=True)

        compile_start = time.time()
        try:
            module = load(
                name=module_name,
                sources=[str(source_path)],
                verbose=False,
                build_directory=str(module_build_dir),
                with_cuda=True,
                extra_cflags=['-O3'],
                extra_cuda_cflags=['-O3'],
            )
        except Exception as exc:
            return {
                'passed': False, 'score': 0.0,
                'compile_seconds': round(time.time() - compile_start, 3),
                'per_size': [],
                'error': f'Compilation failed: {exc}',
            }
        compile_seconds = time.time() - compile_start

        per_size = []
        for dim in self.benchmark_sizes:
            W, X, A, B = self._make_inputs(torch, dim)
            try:
                with torch.no_grad():
                    y_student = module.forward(W, X, A, B)
                    y_ref = self._reference_impl(torch, W, X, A, B)
            except Exception as exc:
                per_size.append({
                    'd': dim, 'passed': False,
                    'error': str(exc),
                })
                del W, X, A, B
                torch.cuda.empty_cache()
                return {
                    'passed': False, 'score': 0.0,
                    'compile_seconds': round(compile_seconds, 3),
                    'per_size': per_size,
                }

            passed, max_abs_err, rel_l2_err = self._check_correctness(
                torch, y_student, y_ref)
            if not passed:
                per_size.append({
                    'd': dim, 'passed': False,
                    'max_abs_err': max_abs_err, 'rel_l2_err': rel_l2_err,
                })
                del W, X, A, B, y_student, y_ref
                torch.cuda.empty_cache()
                return {
                    'passed': False, 'score': 0.0,
                    'compile_seconds': round(compile_seconds, 3),
                    'per_size': per_size,
                }

            student_ms = self._benchmark(
                torch, lambda: module.forward(W, X, A, B))
            torch_ms = self._benchmark(
                torch, lambda: self._reference_impl(torch, W, X, A, B))
            speedup = torch_ms / student_ms if student_ms > 0 else 0.0
            per_size.append({
                'd': dim, 'passed': True,
                'max_abs_err': max_abs_err, 'rel_l2_err': rel_l2_err,
                'student_median_ms': round(student_ms, 4),
                'torch_median_ms': round(torch_ms, 4),
                'speedup': round(speedup, 4),
            })
            del W, X, A, B, y_student, y_ref
            torch.cuda.empty_cache()

        score = self._geometric_mean(
            [e['speedup'] for e in per_size if e.get('passed')])
        return {
            'passed': True,
            'score': round(score, 6),
            'compile_seconds': round(compile_seconds, 3),
            'per_size': per_size,
        }

    def evaluate_config(self, candidate: CandidateConfig,
                        source_path: Path) -> dict[str, Any]:
        result = self.evaluate(candidate.name, source_path,
                               candidate.fingerprint)
        result['candidate'] = candidate.to_dict()
        return result

    @staticmethod
    def _make_inputs(torch, dim: int):
        torch.manual_seed(dim)
        device = 'cuda'
        W = torch.randn(dim, dim, device=device, dtype=torch.float32).contiguous()
        X = torch.randn(dim, dim, device=device, dtype=torch.float32).contiguous()
        A = torch.randn(dim, 16, device=device, dtype=torch.float32).contiguous()
        B = torch.randn(dim, 16, device=device, dtype=torch.float32).contiguous()
        return W, X, A, B

    @staticmethod
    def _reference_impl(torch, W, X, A, B):
        return W @ X + A @ (B.transpose(0, 1).contiguous() @ X)

    @staticmethod
    def _check_correctness(torch, y_student, y_ref):
        diff = (y_student - y_ref).float()
        max_abs_err = diff.abs().max().item()
        rel_l2_err = (diff.norm() / (y_ref.float().norm() + 1e-12)).item()
        passed = torch.allclose(y_student, y_ref, rtol=1e-4, atol=1e-4)
        return passed, max_abs_err, rel_l2_err

    def _benchmark(self, torch, fn):
        for _ in range(self.warmup):
            _ = fn()
        torch.cuda.synchronize()
        timings = []
        for _ in range(self.iters):
            start = torch.cuda.Event(enable_timing=True)
            end = torch.cuda.Event(enable_timing=True)
            start.record()
            _ = fn()
            end.record()
            torch.cuda.synchronize()
            timings.append(start.elapsed_time(end))
        timings.sort()
        return timings[len(timings) // 2]

    @staticmethod
    def _geometric_mean(values: list[float]) -> float:
        if not values:
            return 0.0
        safe = [max(v, 1e-9) for v in values]
        return math.exp(sum(math.log(v) for v in safe) / len(safe))


# =========================================================================
# LLM-driven iterative optimizer (Stage 2)
# =========================================================================

_LLM_SYSTEM_PROMPT = textwrap.dedent("""\
You are a CUDA performance engineer optimising a LoRA forward operator:
  Y = W @ X + A @ (B^T @ X)
where W,X are [d,d] float32, A,B are [d,16] float32, d in [3584,4608].
Target GPU: NVIDIA RTX 3090 (sm_86), CUDA 12.4, PyTorch 2.3.

CRITICAL CONSTRAINT — correctness:
  The evaluation harness compares your output against PyTorch's reference:
    Y_ref = W @ X + A @ (B.transpose(0,1).contiguous() @ X)
  using torch.allclose(Y, Y_ref, rtol=1e-4, atol=1e-4).
  To guarantee bit-exact match you MUST use PyTorch's at::mm / at::addmm
  for matrix multiplications (they call the same cuBLAS path as Python's @).
  DO NOT call cublasSgemm directly — it uses a different accumulation order
  and will fail the correctness check.

Your code must be a single self-contained .cu file that:
  - #include <torch/extension.h> and related headers
  - defines: torch::Tensor forward(torch::Tensor W, X, A, B)
  - ends with PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) { m.def("forward", &forward, ...); }

Allowed optimisations (SAFE — preserve correctness):
  - Stream overlap: run W@X and B^T@X on separate CUDA streams
  - Pre-allocate output tensors with at::empty + at::mm_out / at::addmm_out
  - Make B.t() contiguous before mm to improve memory layout
  - Use at::addmm_out vs separate at::mm + add_
  - Custom CUDA kernels for the small A@tmp (rank-16) accumulation,
    as long as the numerical result matches at::addmm exactly
  - Memory pre-fetching, caching, cudaMemcpyAsync for data staging
  - CUDA graph capture for the entire forward pass

FORBIDDEN (will break correctness or compilation):
  - Direct cublasSgemm calls for the large d×d GEMMs
  - Changing dtype (fp16/bf16/tf32) for the d×d multiplications
  - Approximate or reordered accumulation for W@X

Reply with the COMPLETE .cu file inside a ```cpp code fence.
No partial snippets — the entire file must be compilable.
""").strip()


class LLMIterativeOptimizer:
    """Stage 2: LLM-driven iterative improvement loop."""

    def __init__(self, harness: LoRABenchmarkHarness, build_dir: Path,
                 optimized_path: Path, time_budget_seconds: int):
        self.harness = harness
        self.build_dir = build_dir
        self.optimized_path = optimized_path
        self.time_budget_seconds = time_budget_seconds

    def run(self, current_best_code: str, current_best_score: float,
            stage1_history: list[dict[str, Any]],
            start_time: float) -> list[dict[str, Any]]:
        """Run LLM-driven iterations. Returns iteration history."""
        client = _get_llm()
        if client is None:
            logger.warning('LLM unavailable — skipping Stage 2')
            return []

        history = []
        best_code = current_best_code
        best_score = current_best_score
        iteration = 0
        max_iterations = 5  # Safety cap

        while iteration < max_iterations:
            elapsed = time.time() - start_time
            remaining = self.time_budget_seconds - elapsed
            if remaining < 120:  # Need at least 2 min for compile+bench
                logger.info('Stage 2: insufficient time remaining (%.0fs)',
                            remaining)
                break

            iteration += 1
            logger.info('='*50)
            logger.info('Stage 2 iteration %d (%.0fs elapsed, %.0fs remaining)',
                        iteration, elapsed, remaining)
            logger.info('='*50)

            # Build prompt with current best code and benchmark results
            user_prompt = self._build_prompt(
                best_code, best_score, stage1_history, history, iteration)

            # Ask LLM
            try:
                logger.info('Requesting LLM for improved implementation...')
                llm_response = client.generate_reasoning(
                    system_prompt=_LLM_SYSTEM_PROMPT,
                    user_prompt=user_prompt,
                )
            except Exception as exc:
                logger.warning('LLM call failed: %s', exc)
                history.append({
                    'iteration': iteration,
                    'status': 'llm_error',
                    'error': str(exc),
                })
                continue

            # Extract code
            new_code = LoRACodegen.extract_cuda_from_llm(llm_response)
            if new_code is None:
                logger.warning('Could not extract valid CUDA code from LLM')
                history.append({
                    'iteration': iteration,
                    'status': 'extraction_failed',
                    'llm_response_length': len(llm_response),
                })
                continue

            # Write, compile, benchmark
            source_path = (self.build_dir /
                           f'llm_iter{iteration}_{int(time.time())}.cu')
            source_path.parent.mkdir(parents=True, exist_ok=True)
            source_path.write_text(new_code, encoding='utf-8')

            fp = hashlib.md5(new_code.encode()).hexdigest()[:8]
            result = self.harness.evaluate(
                f'llm_iter{iteration}', source_path, fp)
            result['iteration'] = iteration
            result['status'] = 'benchmarked'

            if result.get('passed') and result.get('score', 0) > 0:
                logger.info('Stage 2 iter %d: PASSED score=%.6f (best=%.6f)',
                            iteration, result['score'], best_score)
                if result['score'] > best_score:
                    logger.info('*** New best! %.6f > %.6f ***',
                                result['score'], best_score)
                    best_score = result['score']
                    best_code = new_code
                    # Write to optimized_lora.cu immediately
                    tmp = self.optimized_path.with_suffix('.cu.tmp')
                    tmp.write_text(best_code, encoding='utf-8')
                    tmp.replace(self.optimized_path)
                    result['is_new_best'] = True
                else:
                    result['is_new_best'] = False
            else:
                logger.info('Stage 2 iter %d: FAILED (passed=%s score=%s)',
                            iteration, result.get('passed'),
                            result.get('score'))
                result['is_new_best'] = False

            history.append(result)

        return history

    def _build_prompt(self, current_code: str, current_score: float,
                      stage1_history: list, stage2_history: list,
                      iteration: int) -> str:
        lines = []
        lines.append(f'## Current best implementation (speedup: {current_score:.4f}x)\n')
        lines.append('```cpp')
        lines.append(current_code)
        lines.append('```\n')

        # Stage 1 summary
        lines.append('## Stage 1 template search results:')
        for entry in stage1_history:
            cand = entry.get('candidate', {})
            name = cand.get('name', '?')
            score = entry.get('score', 0)
            status = entry.get('status', '?')
            lines.append(f'  - {name}: score={score} status={status}')
        lines.append('')

        # Stage 2 history
        if stage2_history:
            lines.append('## Previous LLM iterations:')
            for h in stage2_history:
                it = h.get('iteration', '?')
                sc = h.get('score', 0)
                st = h.get('status', '?')
                best = h.get('is_new_best', False)
                lines.append(f'  - iter {it}: score={sc} status={st}'
                             f'{" (NEW BEST)" if best else ""}')
            lines.append('')

        lines.append(f'## Task (iteration {iteration}):')
        lines.append('Analyse the current implementation and propose an '
                     'improved version that achieves higher speedup while '
                     'maintaining bit-exact correctness with PyTorch\'s '
                     'reference. Focus on:')
        lines.append('  1. Stream overlap strategies')
        lines.append('  2. Memory allocation optimisation')
        lines.append('  3. CUDA graph capture')
        lines.append('  4. Custom rank-16 accumulation kernels')
        lines.append('  5. Any other safe optimisation')
        lines.append('')
        lines.append('Return the COMPLETE .cu file in a ```cpp code fence.')

        return '\n'.join(lines)


# =========================================================================
# Top-level orchestrator
# =========================================================================

class LoRAOptimizationAgent:
    """Two-stage Phase 2 orchestrator.

    Stage 1: fixed template search (fast baseline)
    Stage 2: LLM-driven iterative improvement (if LLM is available)
    """

    def __init__(
        self,
        project_root: str,
        build_dir: str,
        optimized_path: str,
        summary_path: str,
        benchmark_sizes: list[int],
        benchmark_warmup: int,
        benchmark_iters: int,
        search_rounds: int,
        time_budget_seconds: int,
        use_llm: bool = True,
    ):
        self.project_root = Path(project_root)
        self.build_dir = Path(build_dir)
        self.optimized_path = Path(optimized_path)
        self.summary_path = Path(summary_path)
        self.history_path = self.project_root / 'phase2_search_history.json'
        self.benchmark_sizes = benchmark_sizes
        self.search_rounds = search_rounds
        self.time_budget_seconds = time_budget_seconds
        self.use_llm = use_llm
        self.harness = LoRABenchmarkHarness(
            build_dir=self.build_dir / 'phase2',
            benchmark_sizes=benchmark_sizes,
            warmup=benchmark_warmup,
            iters=benchmark_iters,
        )

    def run(self) -> dict[str, Any]:
        start = time.time()
        self.optimized_path.parent.mkdir(parents=True, exist_ok=True)
        self.summary_path.parent.mkdir(parents=True, exist_ok=True)
        self.harness.build_dir.mkdir(parents=True, exist_ok=True)

        gpu_info = utils.get_gpu_info()
        candidates = self._candidate_library()
        initial_candidate = self._baseline_candidate(candidates)
        self._write_candidate(initial_candidate)

        # Check torch availability
        torch_available = self.harness.torch_available()
        if torch_available:
            try:
                torch, _ = self.harness._import_torch()
                torch_available = bool(torch.cuda.is_available())
            except Exception as exc:
                logger.warning('Torch import failed: %s', exc)
                torch_available = False

        # =============================================================
        # Stage 1: Template search
        # =============================================================
        logger.info('=' * 60)
        logger.info('STAGE 1: Template Search (%d candidates)', len(candidates))
        logger.info('=' * 60)

        stage1_history: list[dict[str, Any]] = []
        best_entry: Optional[dict[str, Any]] = None
        best_code: Optional[str] = None

        for candidate in candidates:
            elapsed = time.time() - start
            if elapsed > self.time_budget_seconds * 0.6:
                # Reserve 40% of time budget for Stage 2
                logger.info('Stage 1: reserving time for Stage 2 (%.0fs used)',
                            elapsed)
                break

            source_path = self._write_candidate(
                candidate,
                self.harness.build_dir / f'{candidate.name}_{candidate.fingerprint}.cu',
            )
            if not torch_available:
                stage1_history.append({
                    'candidate': candidate.to_dict(),
                    'passed': None, 'score': None,
                    'status': 'torch_unavailable',
                })
                continue

            try:
                result = self.harness.evaluate_config(candidate, source_path)
                result['status'] = 'benchmarked'
                stage1_history.append(result)
                if result.get('passed'):
                    if (best_entry is None or
                            result['score'] > best_entry['score']):
                        best_entry = result
                        self._write_candidate(candidate)
                        best_code = LoRACodegen.render(candidate)
                logger.info(
                    'Stage 1 | %s: passed=%s score=%s',
                    candidate.name, result.get('passed'), result.get('score'))
            except Exception as exc:
                logger.exception('Candidate %s failed', candidate.name)
                stage1_history.append({
                    'candidate': candidate.to_dict(),
                    'passed': False, 'score': 0.0,
                    'status': 'error', 'error': str(exc),
                })

        if best_entry is None:
            best_entry = {
                'candidate': initial_candidate.to_dict(),
                'passed': None if not torch_available else False,
                'score': None if not torch_available else 0.0,
                'status': ('heuristic_fallback' if not torch_available
                           else 'no_valid_candidate'),
            }
            self._write_candidate(initial_candidate)
            best_code = LoRACodegen.render(initial_candidate)

        best_score = best_entry.get('score', 0.0) or 0.0

        # =============================================================
        # Stage 2: LLM-driven iterative improvement
        # =============================================================
        stage2_history: list[dict[str, Any]] = []

        if (self.use_llm and torch_available and best_code and
                best_score > 0):
            logger.info('=' * 60)
            logger.info('STAGE 2: LLM Iterative Improvement')
            logger.info('Current best score: %.6f', best_score)
            logger.info('=' * 60)

            llm_optimizer = LLMIterativeOptimizer(
                harness=self.harness,
                build_dir=self.harness.build_dir,
                optimized_path=self.optimized_path,
                time_budget_seconds=self.time_budget_seconds,
            )
            stage2_history = llm_optimizer.run(
                current_best_code=best_code,
                current_best_score=best_score,
                stage1_history=stage1_history,
                start_time=start,
            )

            # Update best_entry if Stage 2 improved
            for h in stage2_history:
                if h.get('is_new_best') and h.get('score', 0) > best_score:
                    best_score = h['score']
                    best_entry = {
                        'candidate': {
                            'name': f'llm_iter{h["iteration"]}',
                            'template_name': 'llm_generated',
                        },
                        'passed': True,
                        'score': best_score,
                        'status': 'llm_improved',
                        'per_size': h.get('per_size', []),
                    }
        else:
            if not self.use_llm:
                logger.info('Stage 2 skipped (--skip-llm)')
            elif not torch_available:
                logger.info('Stage 2 skipped (torch unavailable)')
            elif best_score <= 0:
                logger.info('Stage 2 skipped (no valid baseline)')
            else:
                logger.info('Stage 2 skipped (no best code)')

        # =============================================================
        # Final summary
        # =============================================================
        elapsed = time.time() - start
        summary = {
            'phase': 'phase2',
            'gpu_info': gpu_info,
            'torch_available': torch_available,
            'stage1_candidates': len(candidates),
            'stage2_iterations': len(stage2_history),
            'benchmark_sizes': self.benchmark_sizes,
            'time_budget_seconds': self.time_budget_seconds,
            'elapsed_seconds': round(elapsed, 3),
            'best_candidate': best_entry,
            'stage1_history': stage1_history,
            'stage2_history': stage2_history,
            'analysis': self._generate_analysis(
                stage1_history, stage2_history, best_entry),
            'optimized_lora_path': str(self.optimized_path),
        }

        with open(self.history_path, 'w', encoding='utf-8') as f:
            json.dump(summary, f, indent=2, default=str)
        self._write_summary_markdown(summary)
        return summary

    # -----------------------------------------------------------------
    # Candidate library
    # -----------------------------------------------------------------

    def _candidate_library(self) -> list[CandidateConfig]:
        return [
            CandidateConfig(
                template_name='baseline_sequential',
                block_size=None,
                rationale='Single-stream baseline: at::mm + at::addmm, '
                          'no overlap, minimal overhead.',
            ),
            CandidateConfig(
                template_name='dual_stream_overlap',
                block_size=None,
                rationale='Overlaps W@X (main) with B^T@X (aux stream). '
                          'Sync via CUDA event before addmm.',
            ),
            CandidateConfig(
                template_name='dual_stream_pretranspose',
                block_size=None,
                rationale='Dual-stream + explicit B^T contiguous copy '
                          'before mm for better memory access.',
            ),
            CandidateConfig(
                template_name='dual_stream_mm_add',
                block_size=None,
                rationale='Dual-stream + mm + add_ instead of addmm_out '
                          'for final accumulation.',
            ),
            CandidateConfig(
                template_name='triple_stream_prealloc',
                block_size=None,
                rationale='Three streams with pre-allocated outputs. '
                          'W@X and B^T@X fully parallel.',
            ),
            CandidateConfig(
                template_name='sequential_prealloc',
                block_size=None,
                rationale='Single stream + mm_out with pre-allocated '
                          'tensors to avoid allocator overhead.',
            ),
            CandidateConfig(
                template_name='dual_stream_prealloc',
                block_size=None,
                rationale='Dual-stream + pre-allocated outputs via mm_out. '
                          'Combines overlap with zero-alloc.',
            ),
            CandidateConfig(
                template_name='dual_stream_prealloc_contig',
                block_size=None,
                rationale='Dual-stream + pre-alloc + contiguous B^T. '
                          'Tests contig + mm_out combo.',
            ),
        ]

    @staticmethod
    def _baseline_candidate(candidates: list[CandidateConfig]) -> CandidateConfig:
        for c in candidates:
            if c.template_name == 'baseline_sequential':
                return c
        return candidates[0]

    # -----------------------------------------------------------------
    # Analysis
    # -----------------------------------------------------------------

    def _generate_analysis(self, stage1_history: list, stage2_history: list,
                           best_entry: dict) -> str:
        fallback = self._fallback_analysis(
            stage1_history, stage2_history, best_entry)
        if not self.use_llm:
            return fallback

        client = _get_llm()
        if client is None:
            return fallback

        lines = []
        lines.append('Stage 1 results:')
        for e in stage1_history:
            c = e.get('candidate', {})
            lines.append(f"  - {c.get('name')}: score={e.get('score')} "
                         f"status={e.get('status')}")
        if stage2_history:
            lines.append('\nStage 2 (LLM iterations):')
            for h in stage2_history:
                lines.append(f"  - iter {h.get('iteration')}: "
                             f"score={h.get('score')} "
                             f"status={h.get('status')} "
                             f"new_best={h.get('is_new_best')}")

        try:
            return client.generate_reasoning(
                system_prompt=(
                    'Summarise a two-stage LoRA CUDA optimisation search. '
                    'Stage 1 tried fixed templates; Stage 2 used LLM-driven '
                    'iterative improvement. Explain what worked, what did not, '
                    'and where the performance ceiling comes from. '
                    '4-6 concise sentences.'
                ),
                user_prompt=(
                    f"Best: {json.dumps(best_entry, sort_keys=True, default=str)}"
                    f"\n\n{''.join(lines)}"
                ),
            ).strip()
        except Exception as exc:
            logger.warning('LLM analysis failed: %s', exc)
            return fallback

    @staticmethod
    def _fallback_analysis(s1_history, s2_history, best_entry):
        name = best_entry.get('candidate', {}).get('name', 'unknown')
        score = best_entry.get('score')
        s2_count = len(s2_history)
        s2_improved = sum(1 for h in s2_history if h.get('is_new_best'))
        return (
            f"Best variant: {name} (speedup {score}). "
            f"Stage 1 evaluated {len(s1_history)} templates. "
            f"Stage 2 ran {s2_count} LLM iterations, "
            f"{s2_improved} produced improvements. "
            f"The dense W@X GEMM dominates runtime; "
            f"low-rank (r=16) path contributes marginal overhead."
        )

    # -----------------------------------------------------------------
    # File I/O
    # -----------------------------------------------------------------

    def _write_candidate(self, candidate: CandidateConfig,
                         destination: Optional[Path] = None) -> Path:
        destination = destination or self.optimized_path
        source = LoRACodegen.render(candidate)
        destination.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = destination.with_suffix(destination.suffix + '.tmp')
        tmp_path.write_text(source, encoding='utf-8')
        tmp_path.replace(destination)
        return destination

    def _write_summary_markdown(self, summary: dict[str, Any]) -> None:
        best = summary.get('best_candidate', {})
        lines = [
            '# Phase 2 LoRA Optimization Summary', '',
            f'- Elapsed: {summary.get("elapsed_seconds")}s',
            f'- Torch available: {summary.get("torch_available")}',
            f'- Benchmark sizes: {summary.get("benchmark_sizes")}',
            f'- Stage 1 candidates: {summary.get("stage1_candidates")}',
            f'- Stage 2 iterations: {summary.get("stage2_iterations")}',
            f'- Output: {summary.get("optimized_lora_path")}',
            '',
            '## Best Candidate', '',
            f'- Name: {best.get("candidate", {}).get("name")}',
            f'- Status: {best.get("status")}',
            f'- Score: {best.get("score")}',
            '',
            '## Stage 1: Template Search', '',
        ]
        for entry in summary.get('stage1_history', []):
            cand = entry.get('candidate', {})
            bits = []
            for s in entry.get('per_size', []):
                if s.get('passed'):
                    bits.append(f"d={s['d']}:{s.get('speedup')}x")
                else:
                    bits.append(f"d={s['d']}:FAILED")
            suffix = f" ({', '.join(bits)})" if bits else ''
            lines.append(
                f"- {cand.get('name')}: score={entry.get('score')} "
                f"status={entry.get('status')}{suffix}")

        s2 = summary.get('stage2_history', [])
        if s2:
            lines.extend(['', '## Stage 2: LLM Iterative Improvement', ''])
            for h in s2:
                it = h.get('iteration', '?')
                sc = h.get('score', 0)
                st = h.get('status', '?')
                nb = h.get('is_new_best', False)
                bits = []
                for s in h.get('per_size', []):
                    if s.get('passed'):
                        bits.append(f"d={s['d']}:{s.get('speedup')}x")
                    else:
                        bits.append(f"d={s['d']}:FAILED")
                suffix = f" ({', '.join(bits)})" if bits else ''
                lines.append(
                    f"- Iteration {it}: score={sc} status={st}"
                    f"{' **NEW BEST**' if nb else ''}{suffix}")

        lines.extend([
            '', '## Analysis', '',
            summary.get('analysis', ''),
        ])
        self.summary_path.write_text('\n'.join(lines) + '\n',
                                     encoding='utf-8')