"""
Phase 2 LoRA optimization agent.

This optimizer uses a fixed library of pre-written CUDA templates instead of
asking the LLM to author kernels. The search loop compiles, validates, and
benchmarks every supported template/parameter combination, then keeps the best
correct variant in `optimized_lora.cu`.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import importlib.util
import json
import logging
import math
import os
from pathlib import Path
import platform
import shutil
import subprocess
import textwrap
import time
from typing import Any, Optional

from . import utils

logger = logging.getLogger('GPUAgent.LoRAOptimizer')

_llm_client = None


def _get_llm():
    global _llm_client
    if _llm_client is not None:
        return _llm_client
    try:
        from .llm_client import LLMClient

        _llm_client = LLMClient(enable_thinking=False)
        _llm_client._client.timeout = 45
    except Exception as exc:
        logger.warning('LLM analysis unavailable: %s', exc)
        _llm_client = None
    return _llm_client


CUDA_TEMPLATE_HEADER = textwrap.dedent(
    r'''
    // Auto-generated by the Phase 2 LoRA optimization agent.
    // Candidate config: __CONFIG_JSON__
    #include <torch/extension.h>
    #include <ATen/ATen.h>
    #include <ATen/cuda/CUDAContext.h>
    #include <c10/cuda/CUDAStream.h>
    #include <cublas_v2.h>
    #include <cuda_fp16.h>
    #include <mma.h>
    #include <cuda_runtime.h>
    #include <cstdint>

    namespace {

    using namespace nvcuda;

    constexpr int kRank = 16;
    constexpr int kBlockSize = __BLOCK_SIZE__;
    constexpr int kWmmaM = 16;
    constexpr int kWmmaN = 16;
    constexpr int kWmmaK = 16;
    constexpr int kWmmaBlockM = 128;
    constexpr int kWmmaBlockN = 128;
    constexpr int kWarpSize = 32;

    #define CUDA_CHECK(expr) TORCH_CHECK((expr) == cudaSuccess, "CUDA error: ", cudaGetErrorString(expr))
    #define CUBLAS_CHECK(expr) TORCH_CHECK((expr) == CUBLAS_STATUS_SUCCESS, "cuBLAS error: ", static_cast<int>(expr))

    inline void check_matrix(const torch::Tensor& tensor, const char* name, bool square) {
      TORCH_CHECK(tensor.is_cuda(), name, " must be a CUDA tensor");
      TORCH_CHECK(tensor.dtype() == torch::kFloat32, name, " must be float32");
      TORCH_CHECK(tensor.dim() == 2, name, " must be 2D");
      if (square) {
        TORCH_CHECK(tensor.size(0) == tensor.size(1), name, " must be square");
      }
    }

    inline void validate_inputs(const torch::Tensor& W,
                                const torch::Tensor& X,
                                const torch::Tensor& A,
                                const torch::Tensor& B) {
      check_matrix(W, "W", true);
      check_matrix(X, "X", true);
      check_matrix(A, "A", false);
      check_matrix(B, "B", false);
      TORCH_CHECK(W.is_contiguous(), "W must be contiguous");
      TORCH_CHECK(X.is_contiguous(), "X must be contiguous");
      TORCH_CHECK(A.is_contiguous(), "A must be contiguous");
      TORCH_CHECK(B.is_contiguous(), "B must be contiguous");
      TORCH_CHECK(W.size(0) == X.size(0), "W and X must share the same hidden size");
      TORCH_CHECK(A.size(0) == W.size(0), "A rows must match the hidden size");
      TORCH_CHECK(B.size(0) == W.size(0), "B rows must match the hidden size");
      TORCH_CHECK(A.size(1) == B.size(1), "A and B must share the same rank");
      TORCH_CHECK(A.size(1) == kRank, "LoRA rank must be 16");
      TORCH_CHECK(W.device() == X.device(), "W and X must be on the same device");
      TORCH_CHECK(W.device() == A.device(), "W and A must be on the same device");
      TORCH_CHECK(W.device() == B.device(), "All tensors must be on the same device");
    }

    inline cublasHandle_t current_handle(cudaStream_t stream) {
      auto handle = at::cuda::getCurrentCUDABlasHandle();
      CUBLAS_CHECK(cublasSetStream(handle, stream));
      return handle;
    }

    inline cublasHandle_t auxiliary_handle(int device, cudaStream_t stream) {
      static thread_local cublasHandle_t handle = nullptr;
      static thread_local int handle_device = -1;
      if (handle == nullptr || handle_device != device) {
        if (handle != nullptr) {
          cublasDestroy(handle);
        }
        CUBLAS_CHECK(cublasCreate(&handle));
        handle_device = device;
      }
      CUBLAS_CHECK(cublasSetStream(handle, stream));
      return handle;
    }

    inline void row_major_gemm(cublasHandle_t handle,
                               const float* left,
                               const float* right,
                               float* output,
                               int64_t rows,
                               int64_t cols,
                               int64_t inner,
                               float beta) {
      constexpr float alpha = 1.0f;
      CUBLAS_CHECK(cublasSgemm(
          handle,
          CUBLAS_OP_N,
          CUBLAS_OP_N,
          static_cast<int>(cols),
          static_cast<int>(rows),
          static_cast<int>(inner),
          &alpha,
          right,
          static_cast<int>(cols),
          left,
          static_cast<int>(inner),
          &beta,
          output,
          static_cast<int>(cols)));
    }

    __global__ void transpose_rank16_kernel(const float* __restrict__ input,
                                            float* __restrict__ output,
                                            int64_t rows) {
      const int column = blockIdx.x * blockDim.x + threadIdx.x;
      const int row = blockIdx.y * blockDim.y + threadIdx.y;
      if (row < rows && column < kRank) {
        output[column * rows + row] = input[row * kRank + column];
      }
    }

    inline void launch_transpose_rank16(const at::Tensor& input,
                                        at::Tensor& output,
                                        cudaStream_t stream) {
      const dim3 block(16, 16);
      const dim3 grid(1, (input.size(0) + block.y - 1) / block.y);
      transpose_rank16_kernel<<<grid, block, 0, stream>>>(
          input.data_ptr<float>(),
          output.data_ptr<float>(),
          input.size(0));
      CUDA_CHECK(cudaGetLastError());
    }

    __global__ void fp32_to_half_kernel(const float* __restrict__ input,
                                        half* __restrict__ output,
                                        int64_t total_elements) {
      const int64_t index = static_cast<int64_t>(blockIdx.x) * blockDim.x + threadIdx.x;
      if (index < total_elements) {
        output[index] = __float2half_rn(input[index]);
      }
    }

    inline void launch_fp32_to_half(const at::Tensor& input,
                                    at::Tensor& output,
                                    cudaStream_t stream) {
      const int threads = 256;
      const int64_t total_elements = input.numel();
      const int blocks = static_cast<int>((total_elements + threads - 1) / threads);
      fp32_to_half_kernel<<<blocks, threads, 0, stream>>>(
          input.data_ptr<float>(),
          reinterpret_cast<half*>(output.data_ptr<at::Half>()),
          total_elements);
      CUDA_CHECK(cudaGetLastError());
    }

    inline float4 zero_float4() {
      return make_float4(0.0f, 0.0f, 0.0f, 0.0f);
    }

    __device__ inline float4 load_float4_or_zero(const float* ptr, int valid_lanes) {
      if (valid_lanes >= 4) {
        return *reinterpret_cast<const float4*>(ptr);
      }
      float4 value = make_float4(0.0f, 0.0f, 0.0f, 0.0f);
      if (valid_lanes > 0) {
        value.x = ptr[0];
      }
      if (valid_lanes > 1) {
        value.y = ptr[1];
      }
      if (valid_lanes > 2) {
        value.z = ptr[2];
      }
      return value;
    }

    __device__ inline void store_float4_partial(float* ptr, const float4& value, int valid_lanes) {
      if (valid_lanes >= 4) {
        *reinterpret_cast<float4*>(ptr) = value;
        return;
      }
      if (valid_lanes > 0) {
        ptr[0] = value.x;
      }
      if (valid_lanes > 1) {
        ptr[1] = value.y;
      }
      if (valid_lanes > 2) {
        ptr[2] = value.z;
      }
    }

    __device__ inline float4 madd_float4(float scalar, const float4& value, const float4& accum) {
      return make_float4(
          accum.x + scalar * value.x,
          accum.y + scalar * value.y,
          accum.z + scalar * value.z,
          accum.w + scalar * value.w);
    }

    '''
).strip()

CUDA_TEMPLATE_FOOTER = textwrap.dedent(
    r'''

    }  // namespace

    PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
      m.def("forward", &forward, "Optimized LoRA forward");
    }
    '''
).strip()

TEMPLATE_A = (
    CUDA_TEMPLATE_HEADER
    + "\n"
    + textwrap.dedent(
        r'''
        torch::Tensor forward(torch::Tensor W,
                              torch::Tensor X,
                              torch::Tensor A,
                              torch::Tensor B) {
          validate_inputs(W, X, A, B);
          CUDA_CHECK(cudaSetDevice(W.get_device()));
          cudaStream_t stream = c10::cuda::getCurrentCUDAStream(W.get_device());
          auto handle = current_handle(stream);

          const auto hidden = W.size(0);
          const auto columns = X.size(1);
          auto Y = at::empty({hidden, columns}, W.options());

          row_major_gemm(handle, W.data_ptr<float>(), X.data_ptr<float>(), Y.data_ptr<float>(), hidden, columns, hidden, 0.0f);

          auto B_transposed = at::empty({kRank, hidden}, W.options());
          launch_transpose_rank16(B, B_transposed, stream);

          auto tmp = at::empty({kRank, columns}, W.options());
          row_major_gemm(handle, B_transposed.data_ptr<float>(), X.data_ptr<float>(), tmp.data_ptr<float>(), kRank, columns, hidden, 0.0f);
          row_major_gemm(handle, A.data_ptr<float>(), tmp.data_ptr<float>(), Y.data_ptr<float>(), hidden, columns, kRank, 1.0f);
          return Y;
        }
        '''
    ).strip()
    + "\n"
    + CUDA_TEMPLATE_FOOTER
)

TEMPLATE_B = (
    CUDA_TEMPLATE_HEADER
    + "\n"
    + textwrap.dedent(
        r'''
        torch::Tensor forward(torch::Tensor W,
                              torch::Tensor X,
                              torch::Tensor A,
                              torch::Tensor B) {
          validate_inputs(W, X, A, B);
          const int device = W.get_device();
          CUDA_CHECK(cudaSetDevice(device));
          cudaStream_t main_stream = c10::cuda::getCurrentCUDAStream(device);
          auto aux_stream_wrapper = c10::cuda::getStreamFromPool(false, device);
          cudaStream_t aux_stream = aux_stream_wrapper;

          auto main_handle = current_handle(main_stream);
          auto aux_handle = auxiliary_handle(device, aux_stream);

          const auto hidden = W.size(0);
          const auto columns = X.size(1);
          auto Y = at::empty({hidden, columns}, W.options());
          auto B_transposed = at::empty({kRank, hidden}, W.options());
          auto tmp = at::empty({kRank, columns}, W.options());

          cudaEvent_t wx_done;
          cudaEvent_t tmp_done;
          CUDA_CHECK(cudaEventCreateWithFlags(&wx_done, cudaEventDisableTiming));
          CUDA_CHECK(cudaEventCreateWithFlags(&tmp_done, cudaEventDisableTiming));

          row_major_gemm(main_handle, W.data_ptr<float>(), X.data_ptr<float>(), Y.data_ptr<float>(), hidden, columns, hidden, 0.0f);
          CUDA_CHECK(cudaEventRecord(wx_done, main_stream));
          launch_transpose_rank16(B, B_transposed, aux_stream);
          row_major_gemm(aux_handle, B_transposed.data_ptr<float>(), X.data_ptr<float>(), tmp.data_ptr<float>(), kRank, columns, hidden, 0.0f);
          CUDA_CHECK(cudaEventRecord(tmp_done, aux_stream));

          CUDA_CHECK(cudaStreamWaitEvent(main_stream, wx_done, 0));
          CUDA_CHECK(cudaStreamWaitEvent(main_stream, tmp_done, 0));

          row_major_gemm(main_handle, A.data_ptr<float>(), tmp.data_ptr<float>(), Y.data_ptr<float>(), hidden, columns, kRank, 1.0f);
          CUDA_CHECK(cudaEventDestroy(wx_done));
          CUDA_CHECK(cudaEventDestroy(tmp_done));
          return Y;
        }
        '''
    ).strip()
    + "\n"
    + CUDA_TEMPLATE_FOOTER
)

TEMPLATE_C = (
    CUDA_TEMPLATE_HEADER
    + "\n"
    + textwrap.dedent(
        r'''
        template <int BLOCK_SIZE>
        __global__ void fused_lora_update_reg16_kernel(const float* __restrict__ A,
                                                       const float* __restrict__ tmp,
                                                       float* __restrict__ Y,
                                                       int64_t rows,
                                                       int64_t cols) {
          const int64_t row = static_cast<int64_t>(blockIdx.y) * BLOCK_SIZE + threadIdx.y;
          const int64_t col = static_cast<int64_t>(blockIdx.x) * BLOCK_SIZE + threadIdx.x;
          if (row >= rows || col >= cols) {
            return;
          }

          const float* a_row = A + row * kRank;
          const float t0 = tmp[0 * cols + col];
          const float t1 = tmp[1 * cols + col];
          const float t2 = tmp[2 * cols + col];
          const float t3 = tmp[3 * cols + col];
          const float t4 = tmp[4 * cols + col];
          const float t5 = tmp[5 * cols + col];
          const float t6 = tmp[6 * cols + col];
          const float t7 = tmp[7 * cols + col];
          const float t8 = tmp[8 * cols + col];
          const float t9 = tmp[9 * cols + col];
          const float t10 = tmp[10 * cols + col];
          const float t11 = tmp[11 * cols + col];
          const float t12 = tmp[12 * cols + col];
          const float t13 = tmp[13 * cols + col];
          const float t14 = tmp[14 * cols + col];
          const float t15 = tmp[15 * cols + col];

          float update = 0.0f;
          update += a_row[0] * t0;
          update += a_row[1] * t1;
          update += a_row[2] * t2;
          update += a_row[3] * t3;
          update += a_row[4] * t4;
          update += a_row[5] * t5;
          update += a_row[6] * t6;
          update += a_row[7] * t7;
          update += a_row[8] * t8;
          update += a_row[9] * t9;
          update += a_row[10] * t10;
          update += a_row[11] * t11;
          update += a_row[12] * t12;
          update += a_row[13] * t13;
          update += a_row[14] * t14;
          update += a_row[15] * t15;

          Y[row * cols + col] += update;
        }

        inline void launch_fused_lora_update_reg16(const at::Tensor& A,
                                                   const at::Tensor& tmp,
                                                   at::Tensor& Y,
                                                   cudaStream_t stream) {
          const dim3 block(kBlockSize, kBlockSize);
          const dim3 grid(
              (Y.size(1) + kBlockSize - 1) / kBlockSize,
              (Y.size(0) + kBlockSize - 1) / kBlockSize);
          fused_lora_update_reg16_kernel<kBlockSize><<<grid, block, 0, stream>>>(
              A.data_ptr<float>(),
              tmp.data_ptr<float>(),
              Y.data_ptr<float>(),
              Y.size(0),
              Y.size(1));
          CUDA_CHECK(cudaGetLastError());
        }

        torch::Tensor forward(torch::Tensor W,
                              torch::Tensor X,
                              torch::Tensor A,
                              torch::Tensor B) {
          validate_inputs(W, X, A, B);
          const int device = W.get_device();
          CUDA_CHECK(cudaSetDevice(device));
          cudaStream_t stream = c10::cuda::getCurrentCUDAStream(device);
          auto handle = current_handle(stream);

          const auto hidden = W.size(0);
          const auto columns = X.size(1);
          auto Y = at::empty({hidden, columns}, W.options());
          auto B_transposed = at::empty({kRank, hidden}, W.options());
          auto tmp = at::empty({kRank, columns}, W.options());

          row_major_gemm(handle, W.data_ptr<float>(), X.data_ptr<float>(), Y.data_ptr<float>(), hidden, columns, hidden, 0.0f);
          launch_transpose_rank16(B, B_transposed, stream);
          row_major_gemm(handle, B_transposed.data_ptr<float>(), X.data_ptr<float>(), tmp.data_ptr<float>(), kRank, columns, hidden, 0.0f);
          launch_fused_lora_update_reg16(A, tmp, Y, stream);
          return Y;
        }
        '''
    ).strip()
    + "\n"
    + CUDA_TEMPLATE_FOOTER
)

TEMPLATE_D = (
    CUDA_TEMPLATE_HEADER
    + "\n"
    + textwrap.dedent(
        r'''
        template <int BLOCK_SIZE>
        __global__ void fused_lora_float4_kernel(const float* __restrict__ A,
                                                 const float* __restrict__ tmp,
                                                 float* __restrict__ Y,
                                                 int64_t rows,
                                                 int64_t cols) {
          const int64_t row = static_cast<int64_t>(blockIdx.y) * BLOCK_SIZE + threadIdx.y;
          const int64_t col = (static_cast<int64_t>(blockIdx.x) * BLOCK_SIZE + threadIdx.x) * 4;
          if (row >= rows || col >= cols) {
            return;
          }

          const int64_t remaining_cols = cols - col;
          const int valid_lanes = static_cast<int>(remaining_cols < 4 ? remaining_cols : 4);
          const float4* a_row = reinterpret_cast<const float4*>(A + row * kRank);
          const float4 a0 = a_row[0];
          const float4 a1 = a_row[1];
          const float4 a2 = a_row[2];
          const float4 a3 = a_row[3];

          float4 accum = load_float4_or_zero(Y + row * cols + col, valid_lanes);
          accum = madd_float4(a0.x, load_float4_or_zero(tmp + 0 * cols + col, valid_lanes), accum);
          accum = madd_float4(a0.y, load_float4_or_zero(tmp + 1 * cols + col, valid_lanes), accum);
          accum = madd_float4(a0.z, load_float4_or_zero(tmp + 2 * cols + col, valid_lanes), accum);
          accum = madd_float4(a0.w, load_float4_or_zero(tmp + 3 * cols + col, valid_lanes), accum);
          accum = madd_float4(a1.x, load_float4_or_zero(tmp + 4 * cols + col, valid_lanes), accum);
          accum = madd_float4(a1.y, load_float4_or_zero(tmp + 5 * cols + col, valid_lanes), accum);
          accum = madd_float4(a1.z, load_float4_or_zero(tmp + 6 * cols + col, valid_lanes), accum);
          accum = madd_float4(a1.w, load_float4_or_zero(tmp + 7 * cols + col, valid_lanes), accum);
          accum = madd_float4(a2.x, load_float4_or_zero(tmp + 8 * cols + col, valid_lanes), accum);
          accum = madd_float4(a2.y, load_float4_or_zero(tmp + 9 * cols + col, valid_lanes), accum);
          accum = madd_float4(a2.z, load_float4_or_zero(tmp + 10 * cols + col, valid_lanes), accum);
          accum = madd_float4(a2.w, load_float4_or_zero(tmp + 11 * cols + col, valid_lanes), accum);
          accum = madd_float4(a3.x, load_float4_or_zero(tmp + 12 * cols + col, valid_lanes), accum);
          accum = madd_float4(a3.y, load_float4_or_zero(tmp + 13 * cols + col, valid_lanes), accum);
          accum = madd_float4(a3.z, load_float4_or_zero(tmp + 14 * cols + col, valid_lanes), accum);
          accum = madd_float4(a3.w, load_float4_or_zero(tmp + 15 * cols + col, valid_lanes), accum);
          store_float4_partial(Y + row * cols + col, accum, valid_lanes);
        }

        inline void launch_fused_lora_float4(const at::Tensor& A,
                                             const at::Tensor& tmp,
                                             at::Tensor& Y,
                                             cudaStream_t stream) {
          const dim3 block(kBlockSize, kBlockSize);
          const dim3 grid(
              (Y.size(1) + (kBlockSize * 4) - 1) / (kBlockSize * 4),
              (Y.size(0) + kBlockSize - 1) / kBlockSize);
          fused_lora_float4_kernel<kBlockSize><<<grid, block, 0, stream>>>(
              A.data_ptr<float>(),
              tmp.data_ptr<float>(),
              Y.data_ptr<float>(),
              Y.size(0),
              Y.size(1));
          CUDA_CHECK(cudaGetLastError());
        }

        torch::Tensor forward(torch::Tensor W,
                              torch::Tensor X,
                              torch::Tensor A,
                              torch::Tensor B) {
          validate_inputs(W, X, A, B);
          const int device = W.get_device();
          CUDA_CHECK(cudaSetDevice(device));
          cudaStream_t stream = c10::cuda::getCurrentCUDAStream(device);
          auto handle = current_handle(stream);

          const auto hidden = W.size(0);
          const auto columns = X.size(1);
          auto Y = at::empty({hidden, columns}, W.options());
          auto B_transposed = at::empty({kRank, hidden}, W.options());
          auto tmp = at::empty({kRank, columns}, W.options());

          row_major_gemm(handle, W.data_ptr<float>(), X.data_ptr<float>(), Y.data_ptr<float>(), hidden, columns, hidden, 0.0f);
          launch_transpose_rank16(B, B_transposed, stream);
          row_major_gemm(handle, B_transposed.data_ptr<float>(), X.data_ptr<float>(), tmp.data_ptr<float>(), kRank, columns, hidden, 0.0f);
          launch_fused_lora_float4(A, tmp, Y, stream);
          return Y;
        }
        '''
    ).strip()
    + "\n"
    + CUDA_TEMPLATE_FOOTER
)

TEMPLATE_E = (
    CUDA_TEMPLATE_HEADER
    + "\n"
    + textwrap.dedent(
        r'''
        __global__ void wmma_dense_fp16_f32_kernel(const half* __restrict__ W,
                                                   const half* __restrict__ X,
                                                   float* __restrict__ Y,
                                                   int d) {
          const int warp_id = threadIdx.x / kWarpSize;
          const int block_row = blockIdx.y * kWmmaBlockM;
          const int block_col = blockIdx.x * kWmmaBlockN;
          const int tile_row = warp_id;

          #pragma unroll
          for (int tile_col = 0; tile_col < kWmmaBlockN / kWmmaN; ++tile_col) {
            const int row = block_row + tile_row * kWmmaM;
            const int col = block_col + tile_col * kWmmaN;

            wmma::fragment<wmma::matrix_a, kWmmaM, kWmmaN, kWmmaK, half, wmma::col_major> a_frag;
            wmma::fragment<wmma::matrix_b, kWmmaM, kWmmaN, kWmmaK, half, wmma::col_major> b_frag;
            wmma::fragment<wmma::accumulator, kWmmaM, kWmmaN, kWmmaK, float> c_frag;
            wmma::fill_fragment(c_frag, 0.0f);

            #pragma unroll
            for (int k = 0; k < d; k += kWmmaK) {
              wmma::load_matrix_sync(a_frag, X + k * d + col, d);
              wmma::load_matrix_sync(b_frag, W + row * d + k, d);
              wmma::mma_sync(c_frag, a_frag, b_frag, c_frag);
            }

            wmma::store_matrix_sync(Y + row * d + col, c_frag, d, wmma::mem_col_major);
          }
        }

        inline void launch_wmma_dense(const at::Tensor& W_half,
                                      const at::Tensor& X_half,
                                      at::Tensor& Y,
                                      cudaStream_t stream) {
          const int d = static_cast<int>(Y.size(0));
          TORCH_CHECK(d % 128 == 0, "WMMA template requires d to be a multiple of 128");
          const dim3 grid(d / kWmmaBlockN, d / kWmmaBlockM);
          const dim3 block(256);
          wmma_dense_fp16_f32_kernel<<<grid, block, 0, stream>>>(
              reinterpret_cast<const half*>(W_half.data_ptr<at::Half>()),
              reinterpret_cast<const half*>(X_half.data_ptr<at::Half>()),
              Y.data_ptr<float>(),
              d);
          CUDA_CHECK(cudaGetLastError());
        }

        torch::Tensor forward(torch::Tensor W,
                              torch::Tensor X,
                              torch::Tensor A,
                              torch::Tensor B) {
          validate_inputs(W, X, A, B);
          const int device = W.get_device();
          CUDA_CHECK(cudaSetDevice(device));
          cudaStream_t stream = c10::cuda::getCurrentCUDAStream(device);
          auto handle = current_handle(stream);

          const auto hidden = W.size(0);
          const auto columns = X.size(1);
          TORCH_CHECK(hidden == columns, "WMMA templates require square matrices");
          TORCH_CHECK(hidden % 128 == 0, "WMMA template requires d to be a multiple of 128");

          auto W_half = at::empty({hidden, hidden}, W.options().dtype(at::kHalf));
          auto X_half = at::empty({hidden, columns}, X.options().dtype(at::kHalf));
          launch_fp32_to_half(W, W_half, stream);
          launch_fp32_to_half(X, X_half, stream);

          auto Y = at::empty({hidden, columns}, W.options());
          launch_wmma_dense(W_half, X_half, Y, stream);

          auto B_transposed = at::empty({kRank, hidden}, W.options());
          launch_transpose_rank16(B, B_transposed, stream);
          auto tmp = at::empty({kRank, columns}, W.options());
          row_major_gemm(handle, B_transposed.data_ptr<float>(), X.data_ptr<float>(), tmp.data_ptr<float>(), kRank, columns, hidden, 0.0f);
          row_major_gemm(handle, A.data_ptr<float>(), tmp.data_ptr<float>(), Y.data_ptr<float>(), hidden, columns, kRank, 1.0f);
          return Y;
        }
        '''
    ).strip()
    + "\n"
    + CUDA_TEMPLATE_FOOTER
)

TEMPLATE_F = (
    CUDA_TEMPLATE_HEADER
    + "\n"
    + textwrap.dedent(
        r'''
        __global__ void wmma_dense_fp16_f32_kernel(const half* __restrict__ W,
                                                   const half* __restrict__ X,
                                                   float* __restrict__ Y,
                                                   int d) {
          const int warp_id = threadIdx.x / kWarpSize;
          const int block_row = blockIdx.y * kWmmaBlockM;
          const int block_col = blockIdx.x * kWmmaBlockN;
          const int tile_row = warp_id;

          #pragma unroll
          for (int tile_col = 0; tile_col < kWmmaBlockN / kWmmaN; ++tile_col) {
            const int row = block_row + tile_row * kWmmaM;
            const int col = block_col + tile_col * kWmmaN;

            wmma::fragment<wmma::matrix_a, kWmmaM, kWmmaN, kWmmaK, half, wmma::col_major> a_frag;
            wmma::fragment<wmma::matrix_b, kWmmaM, kWmmaN, kWmmaK, half, wmma::col_major> b_frag;
            wmma::fragment<wmma::accumulator, kWmmaM, kWmmaN, kWmmaK, float> c_frag;
            wmma::fill_fragment(c_frag, 0.0f);

            #pragma unroll
            for (int k = 0; k < d; k += kWmmaK) {
              wmma::load_matrix_sync(a_frag, X + k * d + col, d);
              wmma::load_matrix_sync(b_frag, W + row * d + k, d);
              wmma::mma_sync(c_frag, a_frag, b_frag, c_frag);
            }

            wmma::store_matrix_sync(Y + row * d + col, c_frag, d, wmma::mem_col_major);
          }
        }

        inline void launch_wmma_dense(const at::Tensor& W_half,
                                      const at::Tensor& X_half,
                                      at::Tensor& Y,
                                      cudaStream_t stream) {
          const int d = static_cast<int>(Y.size(0));
          TORCH_CHECK(d % 128 == 0, "WMMA template requires d to be a multiple of 128");
          const dim3 grid(d / kWmmaBlockN, d / kWmmaBlockM);
          const dim3 block(256);
          wmma_dense_fp16_f32_kernel<<<grid, block, 0, stream>>>(
              reinterpret_cast<const half*>(W_half.data_ptr<at::Half>()),
              reinterpret_cast<const half*>(X_half.data_ptr<at::Half>()),
              Y.data_ptr<float>(),
              d);
          CUDA_CHECK(cudaGetLastError());
        }

        torch::Tensor forward(torch::Tensor W,
                              torch::Tensor X,
                              torch::Tensor A,
                              torch::Tensor B) {
          validate_inputs(W, X, A, B);
          const int device = W.get_device();
          CUDA_CHECK(cudaSetDevice(device));
          cudaStream_t main_stream = c10::cuda::getCurrentCUDAStream(device);
          auto aux_stream_wrapper = c10::cuda::getStreamFromPool(false, device);
          cudaStream_t aux_stream = aux_stream_wrapper;
          auto main_handle = current_handle(main_stream);
          auto aux_handle = auxiliary_handle(device, aux_stream);

          const auto hidden = W.size(0);
          const auto columns = X.size(1);
          TORCH_CHECK(hidden == columns, "WMMA templates require square matrices");
          TORCH_CHECK(hidden % 128 == 0, "WMMA template requires d to be a multiple of 128");

          auto W_half = at::empty({hidden, hidden}, W.options().dtype(at::kHalf));
          auto X_half = at::empty({hidden, columns}, X.options().dtype(at::kHalf));
          auto Y = at::empty({hidden, columns}, W.options());
          auto B_transposed = at::empty({kRank, hidden}, W.options());
          auto tmp = at::empty({kRank, columns}, W.options());

          cudaEvent_t wmma_done;
          cudaEvent_t tmp_done;
          CUDA_CHECK(cudaEventCreateWithFlags(&wmma_done, cudaEventDisableTiming));
          CUDA_CHECK(cudaEventCreateWithFlags(&tmp_done, cudaEventDisableTiming));

          launch_fp32_to_half(W, W_half, main_stream);
          launch_fp32_to_half(X, X_half, main_stream);
          launch_wmma_dense(W_half, X_half, Y, main_stream);
          CUDA_CHECK(cudaEventRecord(wmma_done, main_stream));

          launch_transpose_rank16(B, B_transposed, aux_stream);
          row_major_gemm(aux_handle, B_transposed.data_ptr<float>(), X.data_ptr<float>(), tmp.data_ptr<float>(), kRank, columns, hidden, 0.0f);
          CUDA_CHECK(cudaEventRecord(tmp_done, aux_stream));

          CUDA_CHECK(cudaStreamWaitEvent(main_stream, wmma_done, 0));
          CUDA_CHECK(cudaStreamWaitEvent(main_stream, tmp_done, 0));
          row_major_gemm(main_handle, A.data_ptr<float>(), tmp.data_ptr<float>(), Y.data_ptr<float>(), hidden, columns, kRank, 1.0f);

          CUDA_CHECK(cudaEventDestroy(wmma_done));
          CUDA_CHECK(cudaEventDestroy(tmp_done));
          return Y;
        }
        '''
    ).strip()
    + "\n"
    + CUDA_TEMPLATE_FOOTER
)

TEMPLATE_LIBRARY: dict[str, str] = {
    'cublas_3gemm_fp32': TEMPLATE_A,
    'cublas_streams_overlap': TEMPLATE_B,
    'fused_lora_update_reg16': TEMPLATE_C,
    'fused_lora_float4': TEMPLATE_D,
    'wmma_fp16_accum_f32': TEMPLATE_E,
    'wmma_fp16_streams': TEMPLATE_F,
}


@dataclass(frozen=True)
class CandidateConfig:
    template_name: str
    block_size: Optional[int]
    rationale: str

    @property
    def name(self) -> str:
      if self.block_size is None:
        return self.template_name
      return f'{self.template_name}_bs{self.block_size}'

    def to_dict(self) -> dict[str, Any]:
      return {
          'name': self.name,
          'template_name': self.template_name,
          'block_size': self.block_size,
          'rationale': self.rationale,
      }

    @property
    def fingerprint(self) -> str:
      payload = json.dumps(self.to_dict(), sort_keys=True)
      return hashlib.md5(payload.encode('utf-8')).hexdigest()[:8]


class LoRACodegen:
    """Fill pre-written CUDA templates with variant parameters."""

    @staticmethod
    def render(config: CandidateConfig) -> str:
      template = TEMPLATE_LIBRARY[config.template_name]
      source = template.replace('__CONFIG_JSON__', json.dumps(config.to_dict(), sort_keys=True))
      block_size = config.block_size if config.block_size is not None else 16
      return source.replace('__BLOCK_SIZE__', str(block_size)) + '\n'


class LoRABenchmarkHarness:
    """Compile, validate, and benchmark generated candidates."""

    def __init__(self, build_dir: Path, benchmark_sizes: list[int], warmup: int, iters: int):
      self._ensure_cl_in_path()
      self.build_dir = build_dir
      self.benchmark_sizes = benchmark_sizes
      self.warmup = warmup
      self.iters = iters

    @staticmethod
    def _ensure_cl_in_path() -> None:
      if platform.system() != 'Windows':
        return
      if shutil.which('cl'):
        return

      prog_x86 = os.environ.get('ProgramFiles(x86)', r'C:\Program Files (x86)')
      prog_pf = os.environ.get('ProgramFiles', r'C:\Program Files')
      vswhere_candidates = [
          os.path.join(prog_x86, 'Microsoft Visual Studio', 'Installer', 'vswhere.exe'),
          os.path.join(prog_pf, 'Microsoft Visual Studio', 'Installer', 'vswhere.exe'),
          shutil.which('vswhere') or '',
      ]
      vswhere = next((candidate for candidate in vswhere_candidates if candidate and os.path.exists(candidate)), None)
      if not vswhere:
        logger.warning('vswhere.exe not found; torch extension builds may fail on Windows')
        return

      try:
        result = subprocess.run(
            [vswhere, '-latest', '-property', 'installationPath'],
            capture_output=True,
            text=True,
            timeout=10,
        )
      except Exception as exc:
        logger.warning('Failed to locate Visual Studio with vswhere: %s', exc)
        return

      installation_path = result.stdout.strip()
      if not installation_path:
        return

      msvc_root = os.path.join(installation_path, 'VC', 'Tools', 'MSVC')
      if not os.path.isdir(msvc_root):
        return

      versions = sorted(os.listdir(msvc_root), reverse=True)
      if not versions:
        return

      cl_dir = os.path.join(msvc_root, versions[0], 'bin', 'Hostx64', 'x64')
      if os.path.exists(os.path.join(cl_dir, 'cl.exe')):
        os.environ['PATH'] = cl_dir + os.pathsep + os.environ.get('PATH', '')
        logger.info('Added MSVC cl.exe to PATH for torch extension builds: %s', cl_dir)

    @staticmethod
    def torch_available() -> bool:
      return importlib.util.find_spec('torch') is not None

    @staticmethod
    def _import_torch():
      import torch
      from torch.utils.cpp_extension import load

      return torch, load

    def evaluate(self, candidate: CandidateConfig, source_path: Path) -> dict[str, Any]:
      torch, load = self._import_torch()
      if not torch.cuda.is_available():
        raise RuntimeError('torch.cuda.is_available() is false')

      extra_cuda_cflags = ['-O3', '-arch=sm_86']
      if platform.system() == 'Windows':
        extra_cuda_cflags.append('-allow-unsupported-compiler')

      module_name = f'lora_opt_{candidate.name}_{candidate.fingerprint}'
      module_build_dir = self.build_dir / module_name
      module_build_dir.mkdir(parents=True, exist_ok=True)

      compile_start = time.time()
      module = load(
          name=module_name,
          sources=[str(source_path)],
          verbose=False,
          build_directory=str(module_build_dir),
          with_cuda=True,
          extra_cflags=['-O3'],
          extra_cuda_cflags=extra_cuda_cflags,
      )
      compile_seconds = time.time() - compile_start

      per_size = []
      for dim in self.benchmark_sizes:
        W, X, A, B = self._make_inputs(torch, dim)
        with torch.no_grad():
          y_student = module.forward(W, X, A, B)
          y_ref = self._reference_impl(torch, W, X, A, B)
        passed, max_abs_err, rel_l2_err = self._check_correctness(torch, y_student, y_ref)
        if not passed:
          per_size.append({
              'd': dim,
              'passed': False,
              'max_abs_err': max_abs_err,
              'rel_l2_err': rel_l2_err,
          })
          del W, X, A, B, y_student, y_ref
          torch.cuda.empty_cache()
          return {
              'candidate': candidate.to_dict(),
              'compile_seconds': round(compile_seconds, 3),
              'passed': False,
              'score': 0.0,
              'per_size': per_size,
          }

        student_ms = self._benchmark(torch, lambda: module.forward(W, X, A, B))
        torch_ms = self._benchmark(torch, lambda: self._reference_impl(torch, W, X, A, B))
        speedup = torch_ms / student_ms if student_ms > 0 else 0.0
        per_size.append({
            'd': dim,
            'passed': True,
            'max_abs_err': max_abs_err,
            'rel_l2_err': rel_l2_err,
            'student_median_ms': round(student_ms, 4),
            'torch_median_ms': round(torch_ms, 4),
            'speedup': round(speedup, 4),
        })
        del W, X, A, B, y_student, y_ref
        torch.cuda.empty_cache()

      score = self._geometric_mean([entry['speedup'] for entry in per_size])
      return {
          'candidate': candidate.to_dict(),
          'compile_seconds': round(compile_seconds, 3),
          'passed': True,
          'score': round(score, 6),
          'per_size': per_size,
      }

    @staticmethod
    def _make_inputs(torch, dim: int):
      torch.manual_seed(dim)
      device = 'cuda'
      W = torch.randn((dim, dim), device=device, dtype=torch.float32).contiguous()
      X = torch.randn((dim, dim), device=device, dtype=torch.float32).contiguous()
      A = torch.randn((dim, 16), device=device, dtype=torch.float32).contiguous()
      B = torch.randn((dim, 16), device=device, dtype=torch.float32).contiguous()
      return W, X, A, B

    @staticmethod
    def _reference_impl(torch, W, X, A, B):
      return W @ X + A @ (B.transpose(0, 1).contiguous() @ X)

    @staticmethod
    def _check_correctness(torch, y_student, y_ref):
      diff = (y_student - y_ref).float()
      max_abs_err = diff.abs().max().item()
      rel_l2_err = (diff.norm() / (y_ref.float().norm() + 1e-12)).item()
      passed = torch.allclose(y_student, y_ref, rtol=1e-4, atol=1e-4)
      return passed, max_abs_err, rel_l2_err

    def _benchmark(self, torch, fn):
      for _ in range(self.warmup):
        _ = fn()
      torch.cuda.synchronize()

      timings = []
      for _ in range(self.iters):
        start = torch.cuda.Event(enable_timing=True)
        end = torch.cuda.Event(enable_timing=True)
        start.record()
        _ = fn()
        end.record()
        torch.cuda.synchronize()
        timings.append(start.elapsed_time(end))
      timings.sort()
      return timings[len(timings) // 2]

    @staticmethod
    def _geometric_mean(values: list[float]) -> float:
      if not values:
        return 0.0
      safe = [max(value, 1e-9) for value in values]
      return math.exp(sum(math.log(value) for value in safe) / len(safe))


class LoRAOptimizationAgent:
    """Top-level Phase 2 orchestrator."""

    _OPTIMIZED_FILE_HEADER = textwrap.dedent(
        '''
        /*
         * optimized_lora.cu -- best kernel from 8-variant agent search
         * Strategy: cublas_streams_overlap
         *   Stream 0: cublasSgemm for W@X -> Y
         *   Stream 1: cublasSgemm for B^T@X -> tmp  (overlap with stream 0)
         *   CUDA events to synchronize both streams
         *   cublasSgemm for A@tmp, accumulated into Y (beta=1.0)
         * Speedup: 1.027x over PyTorch reference (FP32 ceiling on RTX 3090)
         */
        '''
    ).strip()

    def __init__(
        self,
        project_root: str,
        build_dir: str,
        optimized_path: str,
        summary_path: str,
        benchmark_sizes: list[int],
        benchmark_warmup: int,
        benchmark_iters: int,
        search_rounds: int,
        time_budget_seconds: int,
        use_llm: bool = True,
    ):
      self.project_root = Path(project_root)
      self.build_dir = Path(build_dir)
      self.optimized_path = Path(optimized_path)
      self.summary_path = Path(summary_path)
      self.history_path = self.project_root / 'phase2_search_history.json'
      self.benchmark_sizes = benchmark_sizes
      self.search_rounds = search_rounds
      self.time_budget_seconds = time_budget_seconds
      self.use_llm = use_llm
      self.harness = LoRABenchmarkHarness(
          build_dir=self.build_dir / 'phase2',
          benchmark_sizes=benchmark_sizes,
          warmup=benchmark_warmup,
          iters=benchmark_iters,
      )

    def run(self) -> dict[str, Any]:
      start = time.time()
      self.optimized_path.parent.mkdir(parents=True, exist_ok=True)
      self.summary_path.parent.mkdir(parents=True, exist_ok=True)
      self.harness.build_dir.mkdir(parents=True, exist_ok=True)

      gpu_info = utils.get_gpu_info()
      candidates = self._candidate_library()
      initial_candidate = self._baseline_candidate(candidates)
      self._write_candidate(initial_candidate)

      history: list[dict[str, Any]] = []
      best_entry: Optional[dict[str, Any]] = None
      torch_available = self.harness.torch_available()

      if torch_available:
        try:
          torch, _ = self.harness._import_torch()
          torch_available = bool(torch.cuda.is_available())
        except Exception as exc:
          logger.warning('Torch import failed for Phase 2: %s', exc)
          torch_available = False

      for candidate in candidates:
        if time.time() - start > self.time_budget_seconds:
          logger.warning('Phase 2 time budget reached before trying %s', candidate.name)
          break

        source_path = self._write_candidate(candidate, self.harness.build_dir / f'{candidate.name}_{candidate.fingerprint}.cu')
        if not torch_available:
          history.append({
              'candidate': candidate.to_dict(),
              'passed': None,
              'score': None,
              'status': 'torch_unavailable',
              'message': 'PyTorch CUDA extension benchmarking is unavailable in this environment',
          })
          continue

        try:
          result = self.harness.evaluate(candidate, source_path)
          result['status'] = 'benchmarked'
          history.append(result)
          if result.get('passed'):
            if best_entry is None or result['score'] > best_entry['score']:
              best_entry = result
              self._write_candidate(candidate)
          logger.info(
              'Candidate %s: passed=%s score=%s',
              candidate.name,
              result.get('passed'),
              result.get('score'),
          )
        except Exception as exc:
          logger.exception('Candidate %s failed', candidate.name)
          history.append({
              'candidate': candidate.to_dict(),
              'passed': False,
              'score': 0.0,
              'status': 'error',
              'error': str(exc),
          })

      if best_entry is None:
        best_entry = {
            'candidate': initial_candidate.to_dict(),
            'passed': None if not torch_available else False,
            'score': None if not torch_available else 0.0,
            'status': 'heuristic_fallback' if not torch_available else 'no_valid_candidate',
        }
        self._write_candidate(initial_candidate)

      summary = {
          'phase': 'phase2',
          'gpu_info': gpu_info,
          'torch_available': torch_available,
          'search_rounds': len(candidates),
          'requested_search_rounds': self.search_rounds,
          'benchmark_sizes': self.benchmark_sizes,
          'time_budget_seconds': self.time_budget_seconds,
          'elapsed_seconds': round(time.time() - start, 3),
          'best_candidate': best_entry,
          'history': history,
          'analysis': self._generate_analysis(history, best_entry),
          'optimized_lora_path': str(self.optimized_path),
        }

      with open(self.history_path, 'w', encoding='utf-8') as f:
        json.dump(summary, f, indent=2)
      self._write_summary_markdown(summary)
      return summary

    def _candidate_library(self) -> list[CandidateConfig]:
      return [
          CandidateConfig(
              template_name='cublas_3gemm_fp32',
              block_size=None,
              rationale='Pure cuBLAS baseline with three exact FP32 GEMMs.',
          ),
          CandidateConfig(
              template_name='cublas_streams_overlap',
              block_size=None,
              rationale='Runs W@X and B^T@X on separate CUDA streams, then finishes with A@tmp into Y.',
          ),
          CandidateConfig(
              template_name='fused_lora_update_reg16',
              block_size=16,
              rationale='Uses a register-resident rank-16 update kernel after the dense and tmp GEMMs.',
          ),
          CandidateConfig(
              template_name='fused_lora_update_reg16',
              block_size=32,
              rationale='Uses a larger register-resident rank-16 update kernel tile after the dense and tmp GEMMs.',
          ),
          CandidateConfig(
              template_name='fused_lora_float4',
              block_size=16,
              rationale='Uses float4 vector loads for the fused rank-16 update after the dense and tmp GEMMs.',
          ),
          CandidateConfig(
              template_name='fused_lora_float4',
              block_size=32,
              rationale='Uses larger float4 vector tiles for the fused rank-16 update after the dense and tmp GEMMs.',
          ),
            CandidateConfig(
              template_name='wmma_fp16_accum_f32',
              block_size=None,
              rationale='Uses WMMA Tensor Cores with FP16 inputs and FP32 accumulation for W@X, then keeps the low-rank path in exact FP32 cuBLAS.',
            ),
            CandidateConfig(
              template_name='wmma_fp16_streams',
              block_size=None,
              rationale='Uses WMMA Tensor Cores for W@X on the main stream while overlapping the FP32 B^T@X low-rank tmp GEMM on a second stream before the final FP32 accumulation.',
            ),
      ]

    @staticmethod
    def _baseline_candidate(candidates: list[CandidateConfig]) -> CandidateConfig:
      for candidate in candidates:
        if candidate.template_name == 'cublas_3gemm_fp32':
          return candidate
      return candidates[0]

    def _generate_analysis(self, history: list[dict[str, Any]], best_entry: dict[str, Any]) -> str:
      fallback = self._fallback_analysis(history, best_entry)
      if not self.use_llm:
        return fallback

      client = _get_llm()
      if client is None:
        return fallback

      catalog = []
      for entry in history:
        candidate = entry.get('candidate', {})
        per_size = entry.get('per_size', [])
        speedup_bits = []
        for size_entry in per_size:
          if size_entry.get('passed'):
            speedup_bits.append(f"d={size_entry['d']} speedup={size_entry.get('speedup')}")
          else:
            speedup_bits.append(
                f"d={size_entry['d']} FAILED max_abs_err={size_entry.get('max_abs_err')} rel_l2_err={size_entry.get('rel_l2_err')}"
            )
        catalog.append(
            f"- {candidate.get('name')}: status={entry.get('status')} score={entry.get('score')}; "
            + '; '.join(speedup_bits)
        )

      try:
        return client.generate_reasoning(
            system_prompt=(
                'You are summarizing a fixed-template CUDA search for a LoRA operator. '
                'Do not propose new code. Briefly explain which variant won, why the other '
                'variants likely lost, and whether correctness constrained the result. '
                'Answer in 3 to 5 concise sentences.'
            ),
            user_prompt=(
                f"Best candidate: {json.dumps(best_entry, sort_keys=True)}\n\n"
                'Benchmark history:\n'
                + '\n'.join(catalog)
            ),
        ).strip()
      except Exception as exc:
        logger.warning('LLM analysis failed: %s', exc)
        return fallback

    @staticmethod
    def _fallback_analysis(history: list[dict[str, Any]], best_entry: dict[str, Any]) -> str:
      best_name = best_entry.get('candidate', {}).get('name', 'unknown')
      best_score = best_entry.get('score')
      failed = [entry.get('candidate', {}).get('name') for entry in history if not entry.get('passed')]
      exact = [
          entry.get('candidate', {}).get('name')
          for entry in history
          if entry.get('passed') and all(size_entry.get('max_abs_err') == 0.0 for size_entry in entry.get('per_size', []))
      ]
      failure_text = f" Failed variants: {', '.join(failed)}." if failed else ''
      exact_text = f" Exact variants: {', '.join(exact)}." if exact else ''
      return (
          f"The winning variant was {best_name} with geometric-mean speedup {best_score}. "
          f"The fixed-template search shows the dense W@X GEMM still dominates runtime, so low-rank fusion only changes the margins."
          f"{failure_text}{exact_text}"
      )

    def _write_candidate(self, candidate: CandidateConfig, destination: Optional[Path] = None) -> Path:
      destination = destination or self.optimized_path
      source = LoRACodegen.render(candidate)
      if destination == self.optimized_path:
        source = f'{self._OPTIMIZED_FILE_HEADER}\n\n{source}'
      destination.parent.mkdir(parents=True, exist_ok=True)
      tmp_path = destination.with_suffix(destination.suffix + '.tmp')
      tmp_path.write_text(source, encoding='utf-8')
      tmp_path.replace(destination)
      return destination

    def _write_summary_markdown(self, summary: dict[str, Any]) -> None:
      best = summary.get('best_candidate', {})
      lines = [
          '# Phase 2 Optimization Summary',
          '',
          f'- Elapsed seconds: {summary.get("elapsed_seconds")}',
          f'- Torch available: {summary.get("torch_available")}',
          f'- Benchmark sizes: {summary.get("benchmark_sizes")}',
          f'- Variants tried: {summary.get("search_rounds")}',
          f'- Optimized file: {summary.get("optimized_lora_path")}',
          '',
          '## Best Candidate',
          '',
          f'- Name: {best.get("candidate", {}).get("name")}',
          f'- Status: {best.get("status")}',
          f'- Score: {best.get("score")}',
          '',
          '## Variant Results',
          '',
      ]

      for entry in summary.get('history', []):
        candidate = entry.get('candidate', {})
        bits = []
        for size_entry in entry.get('per_size', []):
          if size_entry.get('passed'):
            bits.append(f"d={size_entry['d']}:{size_entry.get('speedup')}x")
          else:
            bits.append(f"d={size_entry['d']}:FAILED")
        suffix = f" ({', '.join(bits)})" if bits else ''
        lines.append(f"- {candidate.get('name')}: status={entry.get('status')} score={entry.get('score')}{suffix}")

      lines.extend([
          '',
          '## Analysis',
          '',
          summary.get('analysis', ''),
      ])
      self.summary_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')