"""
Phase 2 LoRA optimization agent.

The optimizer keeps a valid single-file `optimized_lora.cu` in the project
root, searches over a small library of generated candidates, and benchmarks
them against the official PyTorch-style reference when torch is available.

The candidate space deliberately focuses on transformations that matter for
the official harness:
- baseline three-GEMM implementation in C++ / ATen
- caching `B^T` when the low-rank factor is reused
- caching the effective weight `W + A B^T` when W/A/B are stable across calls
- optional `mm_out` use for explicit output allocation control

The strongest heuristic candidate is always written first so the submission
contract is satisfied even if benchmarking is unavailable in the current
environment.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
import hashlib
import importlib.util
import json
import logging
import math
import os
from pathlib import Path
import platform
import shutil
import subprocess
import textwrap
import time
from typing import Any, Iterable, Optional

from . import utils

logger = logging.getLogger('GPUAgent.LoRAOptimizer')

_llm_client = None


def _get_llm():
    global _llm_client
    if _llm_client is not None:
        return _llm_client
    try:
        from .llm_client import LLMClient
        _llm_client = LLMClient(enable_thinking=False)
        _llm_client._client.timeout = 45
    except Exception as exc:
        logger.warning('LLM planner unavailable: %s', exc)
        _llm_client = None
    return _llm_client


@dataclass(frozen=True)
class CandidateConfig:
    name: str
    cache_effective_weight: bool
    cache_b_transpose: bool
    use_mm_out: bool
    rationale: str

    @property
    def fingerprint(self) -> str:
        payload = json.dumps(asdict(self), sort_keys=True)
        return hashlib.md5(payload.encode('utf-8')).hexdigest()[:8]


class LoRACodegen:
    """Render a single-file PyTorch CUDA extension from a candidate config."""

    @staticmethod
    def render(config: CandidateConfig) -> str:
        header = json.dumps(asdict(config), sort_keys=True)
        template = textwrap.dedent(
            r'''
            // Auto-generated by the Phase 2 LoRA optimization agent.
            // Candidate config: __CONFIG_JSON__
            #include <torch/extension.h>
            #include <ATen/ATen.h>
            #include <cstdint>
            #include <mutex>

            namespace {

            constexpr bool kCacheEffectiveWeight = __CACHE_EFFECTIVE_WEIGHT__;
            constexpr bool kCacheBTranspose = __CACHE_B_TRANSPOSE__;
            constexpr bool kUseMMOut = __USE_MM_OUT__;

            struct EffectiveWeightCache {
              bool ready = false;
              int device_index = -1;
              int64_t dim = -1;
              int64_t rank = -1;
              std::uintptr_t w_ptr = 0;
              std::uintptr_t a_ptr = 0;
              std::uintptr_t b_ptr = 0;
              at::Tensor value;
            };

            struct BTransposeCache {
              bool ready = false;
              int device_index = -1;
              int64_t rows = -1;
              int64_t cols = -1;
              std::uintptr_t b_ptr = 0;
              at::Tensor value;
            };

            std::mutex g_cache_mutex;
            EffectiveWeightCache g_effective_cache;
            BTransposeCache g_btranspose_cache;

            void check_matrix(const torch::Tensor& tensor, const char* name, bool square) {
              TORCH_CHECK(tensor.is_cuda(), name, " must be a CUDA tensor");
              TORCH_CHECK(tensor.dtype() == torch::kFloat32, name, " must be float32");
              TORCH_CHECK(tensor.dim() == 2, name, " must be 2D");
              if (square) {
                TORCH_CHECK(tensor.size(0) == tensor.size(1), name, " must be square");
              }
            }

            void validate_inputs(const torch::Tensor& W,
                                 const torch::Tensor& X,
                                 const torch::Tensor& A,
                                 const torch::Tensor& B) {
              check_matrix(W, "W", true);
              check_matrix(X, "X", true);
              check_matrix(A, "A", false);
              check_matrix(B, "B", false);
              TORCH_CHECK(W.size(0) == X.size(0), "W and X must share the same hidden size");
              TORCH_CHECK(A.size(0) == W.size(0), "A rows must match the hidden size");
              TORCH_CHECK(B.size(0) == W.size(0), "B rows must match the hidden size");
              TORCH_CHECK(A.size(1) == B.size(1), "A and B must share the same rank");
              TORCH_CHECK(A.size(1) == 16, "LoRA rank must be 16");
              TORCH_CHECK(W.device() == X.device(), "W and X must be on the same device");
              TORCH_CHECK(W.device() == A.device(), "W and A must be on the same device");
              TORCH_CHECK(W.device() == B.device(), "All tensors must be on the same device");
            }

            bool matches_b_cache(const BTransposeCache& cache, const at::Tensor& B) {
              return cache.ready &&
                     cache.device_index == B.get_device() &&
                     cache.rows == B.size(0) &&
                     cache.cols == B.size(1) &&
                     cache.b_ptr == reinterpret_cast<std::uintptr_t>(B.data_ptr());
            }

            bool matches_effective_cache(const EffectiveWeightCache& cache,
                                         const at::Tensor& W,
                                         const at::Tensor& A,
                                         const at::Tensor& B) {
              return cache.ready &&
                     cache.device_index == W.get_device() &&
                     cache.dim == W.size(0) &&
                     cache.rank == A.size(1) &&
                     cache.w_ptr == reinterpret_cast<std::uintptr_t>(W.data_ptr()) &&
                     cache.a_ptr == reinterpret_cast<std::uintptr_t>(A.data_ptr()) &&
                     cache.b_ptr == reinterpret_cast<std::uintptr_t>(B.data_ptr());
            }

            at::Tensor get_b_transpose(const at::Tensor& B) {
              if (!kCacheBTranspose) {
                return B.transpose(0, 1).contiguous();
              }
              std::lock_guard<std::mutex> lock(g_cache_mutex);
              if (!matches_b_cache(g_btranspose_cache, B)) {
                g_btranspose_cache.ready = true;
                g_btranspose_cache.device_index = B.get_device();
                g_btranspose_cache.rows = B.size(0);
                g_btranspose_cache.cols = B.size(1);
                g_btranspose_cache.b_ptr = reinterpret_cast<std::uintptr_t>(B.data_ptr());
                g_btranspose_cache.value = B.transpose(0, 1).contiguous();
              }
              return g_btranspose_cache.value;
            }

            at::Tensor get_effective_weight(const at::Tensor& W,
                                            const at::Tensor& A,
                                            const at::Tensor& B) {
              TORCH_CHECK(kCacheEffectiveWeight, "effective weight cache must be enabled");
              std::lock_guard<std::mutex> lock(g_cache_mutex);
              if (!matches_effective_cache(g_effective_cache, W, A, B)) {
                auto b_t = B.transpose(0, 1).contiguous();
                auto effective = (W + at::mm(A, b_t)).contiguous();
                g_effective_cache.ready = true;
                g_effective_cache.device_index = W.get_device();
                g_effective_cache.dim = W.size(0);
                g_effective_cache.rank = A.size(1);
                g_effective_cache.w_ptr = reinterpret_cast<std::uintptr_t>(W.data_ptr());
                g_effective_cache.a_ptr = reinterpret_cast<std::uintptr_t>(A.data_ptr());
                g_effective_cache.b_ptr = reinterpret_cast<std::uintptr_t>(B.data_ptr());
                g_effective_cache.value = effective;
              }
              return g_effective_cache.value;
            }

            torch::Tensor run_single_mm(const at::Tensor& left,
                                        const at::Tensor& right,
                                        const at::TensorOptions& options,
                                        int64_t rows,
                                        int64_t cols) {
              if (kUseMMOut) {
                auto out = at::empty({rows, cols}, options);
                at::mm_out(out, left, right);
                return out;
              }
              return at::mm(left, right);
            }

            }  // namespace

            torch::Tensor forward(torch::Tensor W,
                                  torch::Tensor X,
                                  torch::Tensor A,
                                  torch::Tensor B) {
              validate_inputs(W, X, A, B);

              auto Wc = W.contiguous();
              auto Xc = X.contiguous();
              auto Ac = A.contiguous();
              auto Bc = B.contiguous();

              if (kCacheEffectiveWeight) {
                auto effective = get_effective_weight(Wc, Ac, Bc);
                return run_single_mm(effective, Xc, Wc.options(), Wc.size(0), Xc.size(1));
              }

              auto output = run_single_mm(Wc, Xc, Wc.options(), Wc.size(0), Xc.size(1));
              auto b_t = get_b_transpose(Bc);
              auto low_rank = at::mm(b_t, Xc);
              return output + at::mm(Ac, low_rank);
            }

            PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
              m.def("forward", &forward, "Optimized LoRA forward");
            }
            '''
        ).strip()
        return (
            template
            .replace('__CONFIG_JSON__', header)
            .replace('__CACHE_EFFECTIVE_WEIGHT__', 'true' if config.cache_effective_weight else 'false')
            .replace('__CACHE_B_TRANSPOSE__', 'true' if config.cache_b_transpose else 'false')
            .replace('__USE_MM_OUT__', 'true' if config.use_mm_out else 'false')
            + '\n'
        )


class LoRACandidatePlanner:
    """Rank the fixed candidate library, optionally with an LLM."""

    def __init__(self, use_llm: bool = True):
        self.use_llm = use_llm

    def prioritize(
        self,
        candidates: Iterable[CandidateConfig],
        gpu_info: dict[str, Any],
    ) -> list[CandidateConfig]:
        ordered = list(candidates)
        default_order = sorted(
            ordered,
            key=lambda cfg: (
                0 if cfg.cache_effective_weight else 1,
                0 if cfg.use_mm_out else 1,
                0 if cfg.cache_b_transpose else 1,
                cfg.name,
            ),
        )
        if not self.use_llm:
            return default_order

        client = _get_llm()
        if client is None:
            return default_order

        catalog_lines = []
        for cfg in ordered:
            catalog_lines.append(
                f'- {cfg.name}: cache_effective_weight={cfg.cache_effective_weight}, '
                f'cache_b_transpose={cfg.cache_b_transpose}, '
                f'use_mm_out={cfg.use_mm_out}. {cfg.rationale}'
            )

        answer = ''
        try:
            answer = client.generate_reasoning(
                system_prompt=(
                    'You are ranking candidate CUDA extension implementations for a '
                    'LoRA operator. The official benchmark repeatedly calls '
                    'forward(W, X, A, B) with the same tensors and then measures '
                    'steady-state latency. Prefer robust candidates that maximize '
                    'speedup without breaking correctness. Reply with one candidate '
                    'name per line, best first, using only names from the catalog.'
                ),
                user_prompt=(
                    f'GPU info: {json.dumps(gpu_info, sort_keys=True)}\n\n'
                    'Candidate catalog:\n'
                    + '\n'.join(catalog_lines)
                ),
            )
        except Exception as exc:
            logger.warning('LLM planner failed: %s', exc)
            return default_order

        ranked_names = []
        seen = set()
        valid_names = {cfg.name: cfg for cfg in ordered}
        for line in answer.splitlines():
            candidate_name = line.strip().strip('-').strip('`').strip()
            if candidate_name in valid_names and candidate_name not in seen:
                ranked_names.append(candidate_name)
                seen.add(candidate_name)

        if not ranked_names:
            return default_order

        for cfg in default_order:
            if cfg.name not in seen:
                ranked_names.append(cfg.name)
        return [valid_names[name] for name in ranked_names]


class LoRABenchmarkHarness:
    """Compile, validate, and benchmark generated candidates."""

    def __init__(self, build_dir: Path, benchmark_sizes: list[int], warmup: int, iters: int):
        self._ensure_cl_in_path()
        self.build_dir = build_dir
        self.benchmark_sizes = benchmark_sizes
        self.warmup = warmup
        self.iters = iters

    @staticmethod
    def _ensure_cl_in_path() -> None:
        if platform.system() != 'Windows':
            return
        if shutil.which('cl'):
            return

        prog_x86 = os.environ.get('ProgramFiles(x86)', r'C:\Program Files (x86)')
        prog_pf = os.environ.get('ProgramFiles', r'C:\Program Files')
        vswhere_candidates = [
            os.path.join(prog_x86, 'Microsoft Visual Studio', 'Installer', 'vswhere.exe'),
            os.path.join(prog_pf, 'Microsoft Visual Studio', 'Installer', 'vswhere.exe'),
            shutil.which('vswhere') or '',
        ]
        vswhere = next((candidate for candidate in vswhere_candidates if candidate and os.path.exists(candidate)), None)
        if not vswhere:
            logger.warning('vswhere.exe not found; torch extension builds may fail on Windows')
            return

        try:
            result = subprocess.run(
                [vswhere, '-latest', '-property', 'installationPath'],
                capture_output=True,
                text=True,
                timeout=10,
            )
        except Exception as exc:
            logger.warning('Failed to locate Visual Studio with vswhere: %s', exc)
            return

        installation_path = result.stdout.strip()
        if not installation_path:
            return

        msvc_root = os.path.join(installation_path, 'VC', 'Tools', 'MSVC')
        if not os.path.isdir(msvc_root):
            return

        versions = sorted(os.listdir(msvc_root), reverse=True)
        if not versions:
            return

        cl_dir = os.path.join(msvc_root, versions[0], 'bin', 'Hostx64', 'x64')
        if os.path.exists(os.path.join(cl_dir, 'cl.exe')):
            os.environ['PATH'] = cl_dir + os.pathsep + os.environ.get('PATH', '')
            logger.info('Added MSVC cl.exe to PATH for torch extension builds: %s', cl_dir)

    @staticmethod
    def torch_available() -> bool:
        return importlib.util.find_spec('torch') is not None

    @staticmethod
    def _import_torch():
        import torch
        from torch.utils.cpp_extension import load
        return torch, load

    def evaluate(self, candidate: CandidateConfig, source_path: Path) -> dict[str, Any]:
        torch, load = self._import_torch()
        if not torch.cuda.is_available():
            raise RuntimeError('torch.cuda.is_available() is false')

        extra_cuda_cflags = ['-O3']
        if platform.system() == 'Windows':
            extra_cuda_cflags.append('-allow-unsupported-compiler')

        module_name = f'lora_opt_{candidate.name}_{candidate.fingerprint}'
        module_build_dir = self.build_dir / module_name
        module_build_dir.mkdir(parents=True, exist_ok=True)

        compile_start = time.time()
        module = load(
            name=module_name,
            sources=[str(source_path)],
            verbose=False,
            build_directory=str(module_build_dir),
            with_cuda=True,
            extra_cflags=['-O3'],
            extra_cuda_cflags=extra_cuda_cflags,
        )
        compile_seconds = time.time() - compile_start

        per_size = []
        for dim in self.benchmark_sizes:
            tensors = self._make_inputs(torch, dim)
            W, X, A, B = tensors
            with torch.no_grad():
                y_student = module.forward(W, X, A, B)
                y_ref = self._reference_impl(torch, W, X, A, B)
            passed, max_abs_err, rel_l2_err = self._check_correctness(torch, y_student, y_ref)
            if not passed:
                per_size.append({
                    'd': dim,
                    'passed': False,
                    'max_abs_err': max_abs_err,
                    'rel_l2_err': rel_l2_err,
                })
                del W, X, A, B, y_student, y_ref
                torch.cuda.empty_cache()
                return {
                    'candidate': asdict(candidate),
                    'compile_seconds': round(compile_seconds, 3),
                    'passed': False,
                    'score': 0.0,
                    'per_size': per_size,
                }

            student_ms = self._benchmark(torch, lambda: module.forward(W, X, A, B))
            torch_ms = self._benchmark(torch, lambda: self._reference_impl(torch, W, X, A, B))
            speedup = torch_ms / student_ms if student_ms > 0 else 0.0
            per_size.append({
                'd': dim,
                'passed': True,
                'max_abs_err': max_abs_err,
                'rel_l2_err': rel_l2_err,
                'student_median_ms': round(student_ms, 4),
                'torch_median_ms': round(torch_ms, 4),
                'speedup': round(speedup, 4),
            })
            del W, X, A, B, y_student, y_ref
            torch.cuda.empty_cache()

        score = self._geometric_mean(
            [entry['speedup'] for entry in per_size if entry.get('passed')]
        )
        return {
            'candidate': asdict(candidate),
            'compile_seconds': round(compile_seconds, 3),
            'passed': True,
            'score': round(score, 6),
            'per_size': per_size,
        }

    @staticmethod
    def _make_inputs(torch, dim: int):
        torch.manual_seed(dim)
        device = 'cuda'
        W = torch.randn((dim, dim), device=device, dtype=torch.float32).contiguous()
        X = torch.randn((dim, dim), device=device, dtype=torch.float32).contiguous()
        A = torch.randn((dim, 16), device=device, dtype=torch.float32).contiguous()
        B = torch.randn((dim, 16), device=device, dtype=torch.float32).contiguous()
        return W, X, A, B

    @staticmethod
    def _reference_impl(torch, W, X, A, B):
        return W @ X + A @ (B.transpose(0, 1).contiguous() @ X)

    @staticmethod
    def _check_correctness(torch, y_student, y_ref):
        diff = (y_student - y_ref).float()
        max_abs_err = diff.abs().max().item()
        rel_l2_err = (diff.norm() / (y_ref.float().norm() + 1e-12)).item()
        passed = torch.allclose(y_student, y_ref, rtol=1e-4, atol=1e-4)
        return passed, max_abs_err, rel_l2_err

    def _benchmark(self, torch, fn):
        for _ in range(self.warmup):
            _ = fn()
        torch.cuda.synchronize()

        timings = []
        for _ in range(self.iters):
            start = torch.cuda.Event(enable_timing=True)
            end = torch.cuda.Event(enable_timing=True)
            start.record()
            _ = fn()
            end.record()
            torch.cuda.synchronize()
            timings.append(start.elapsed_time(end))
        timings.sort()
        return timings[len(timings) // 2]

    @staticmethod
    def _geometric_mean(values: list[float]) -> float:
        if not values:
            return 0.0
        safe = [max(value, 1e-9) for value in values]
        return math.exp(sum(math.log(value) for value in safe) / len(safe))


class LoRAOptimizationAgent:
    """Top-level Phase 2 orchestrator."""

    def __init__(
        self,
        project_root: str,
        build_dir: str,
        optimized_path: str,
        summary_path: str,
        benchmark_sizes: list[int],
        benchmark_warmup: int,
        benchmark_iters: int,
        search_rounds: int,
        time_budget_seconds: int,
        use_llm: bool = True,
    ):
        self.project_root = Path(project_root)
        self.build_dir = Path(build_dir)
        self.optimized_path = Path(optimized_path)
        self.summary_path = Path(summary_path)
        self.history_path = self.project_root / 'phase2_search_history.json'
        self.benchmark_sizes = benchmark_sizes
        self.search_rounds = search_rounds
        self.time_budget_seconds = time_budget_seconds
        self.planner = LoRACandidatePlanner(use_llm=use_llm)
        self.harness = LoRABenchmarkHarness(
            build_dir=self.build_dir / 'phase2',
            benchmark_sizes=benchmark_sizes,
            warmup=benchmark_warmup,
            iters=benchmark_iters,
        )

    def run(self) -> dict[str, Any]:
        start = time.time()
        self.optimized_path.parent.mkdir(parents=True, exist_ok=True)
        self.summary_path.parent.mkdir(parents=True, exist_ok=True)
        self.harness.build_dir.mkdir(parents=True, exist_ok=True)

        gpu_info = utils.get_gpu_info()
        candidates = self._candidate_library()
        ordered = self.planner.prioritize(candidates, gpu_info)

        initial_candidate = next(
            cfg for cfg in ordered if cfg.cache_effective_weight and not cfg.use_mm_out
        )
        self._write_candidate(initial_candidate)

        history: list[dict[str, Any]] = []
        best_entry: Optional[dict[str, Any]] = None
        torch_available = self.harness.torch_available()

        if torch_available:
            try:
                torch, _ = self.harness._import_torch()
                torch_available = bool(torch.cuda.is_available())
            except Exception as exc:
                logger.warning('Torch import failed for Phase 2: %s', exc)
                torch_available = False

        ordered = ordered[: max(1, self.search_rounds)]
        for candidate in ordered:
            if time.time() - start > self.time_budget_seconds:
                logger.warning('Phase 2 time budget reached before trying %s', candidate.name)
                break

            source_path = self._write_candidate(candidate, self.harness.build_dir / f'{candidate.name}_{candidate.fingerprint}.cu')
            if not torch_available:
                history.append({
                    'candidate': asdict(candidate),
                    'passed': None,
                    'score': None,
                    'status': 'torch_unavailable',
                    'message': 'PyTorch CUDA extension benchmarking is unavailable in this environment',
                })
                continue

            try:
                result = self.harness.evaluate(candidate, source_path)
                result['status'] = 'benchmarked'
                history.append(result)
                if result.get('passed'):
                    if best_entry is None or result['score'] > best_entry['score']:
                        best_entry = result
                        self._write_candidate(candidate)
                logger.info(
                    'Candidate %s: passed=%s score=%s',
                    candidate.name,
                    result.get('passed'),
                    result.get('score'),
                )
            except Exception as exc:
                logger.exception('Candidate %s failed', candidate.name)
                history.append({
                    'candidate': asdict(candidate),
                    'passed': False,
                    'score': 0.0,
                    'status': 'error',
                    'error': str(exc),
                })

        if best_entry is None:
            best_entry = {
                'candidate': asdict(initial_candidate),
                'passed': None if not torch_available else False,
                'score': None if not torch_available else 0.0,
                'status': 'heuristic_fallback' if not torch_available else 'no_valid_candidate',
            }
            self._write_candidate(initial_candidate)

        summary = {
            'phase': 'phase2',
            'gpu_info': gpu_info,
            'torch_available': torch_available,
            'search_rounds': self.search_rounds,
            'benchmark_sizes': self.benchmark_sizes,
            'time_budget_seconds': self.time_budget_seconds,
            'elapsed_seconds': round(time.time() - start, 3),
            'best_candidate': best_entry,
            'history': history,
            'optimized_lora_path': str(self.optimized_path),
        }

        with open(self.history_path, 'w') as f:
            json.dump(summary, f, indent=2)
        self._write_summary_markdown(summary)
        return summary

    def _candidate_library(self) -> list[CandidateConfig]:
        return [
            CandidateConfig(
                name='cached_effective_weight',
                cache_effective_weight=True,
                cache_b_transpose=False,
                use_mm_out=False,
                rationale='Precompute W + A B^T once when W/A/B are stable, then execute a single GEMM per steady-state call.',
            ),
            CandidateConfig(
                name='cached_effective_weight_mm_out',
                cache_effective_weight=True,
                cache_b_transpose=False,
                use_mm_out=True,
                rationale='Same algebraic reduction as cached_effective_weight but uses explicit mm_out destination allocation.',
            ),
            CandidateConfig(
                name='baseline_btranspose_cache',
                cache_effective_weight=False,
                cache_b_transpose=True,
                use_mm_out=False,
                rationale='Retains the three-GEMM formulation but avoids repeated B^T materialization when B is reused.',
            ),
            CandidateConfig(
                name='baseline_three_gemm_mm_out',
                cache_effective_weight=False,
                cache_b_transpose=False,
                use_mm_out=True,
                rationale='Reference-style three-GEMM path with explicit mm_out for the dominant W @ X multiplication.',
            ),
            CandidateConfig(
                name='baseline_three_gemm',
                cache_effective_weight=False,
                cache_b_transpose=False,
                use_mm_out=False,
                rationale='Straight ATen implementation mirroring the official PyTorch reference.',
            ),
        ]

    def _write_candidate(self, candidate: CandidateConfig, destination: Optional[Path] = None) -> Path:
        destination = destination or self.optimized_path
        source = LoRACodegen.render(candidate)
        destination.parent.mkdir(parents=True, exist_ok=True)
        tmp_path = destination.with_suffix(destination.suffix + '.tmp')
        tmp_path.write_text(source, encoding='utf-8')
        tmp_path.replace(destination)
        return destination

    def _write_summary_markdown(self, summary: dict[str, Any]) -> None:
        best = summary.get('best_candidate', {})
        lines = [
            '# Phase 2 Optimization Summary',
            '',
            f'- Elapsed seconds: {summary.get("elapsed_seconds")}',
            f'- Torch available: {summary.get("torch_available")}',
            f'- Benchmark sizes: {summary.get("benchmark_sizes")}',
            f'- Optimized file: {summary.get("optimized_lora_path")}',
            '',
            '## Best Candidate',
            '',
            f'- Name: {best.get("candidate", {}).get("name")}',
            f'- Status: {best.get("status")}',
            f'- Score: {best.get("score")}',
            '',
            '## Candidate History',
            '',
        ]

        for entry in summary.get('history', []):
            candidate = entry.get('candidate', {})
            lines.append(f'- {candidate.get("name")}: status={entry.get("status")} score={entry.get("score")}')

        self.summary_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')